{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from scipy.stats import wilcoxon\n",
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "from sklearn.model_selection import RepeatedStratifiedKFold\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "import xgboost as xgb\n",
    "\n",
    "\n",
    "from sfc import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>dg</th>\n",
       "      <th>bt</th>\n",
       "      <th>cl</th>\n",
       "      <th>burts</th>\n",
       "      <th>pr</th>\n",
       "      <th>auth</th>\n",
       "      <th>areaSAS</th>\n",
       "      <th>areaSES</th>\n",
       "      <th>relSESA</th>\n",
       "      <th>consurf</th>\n",
       "      <th>type</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>0.000757</td>\n",
       "      <td>0.196523</td>\n",
       "      <td>1.996053</td>\n",
       "      <td>0.001401</td>\n",
       "      <td>0.046619</td>\n",
       "      <td>91.970392</td>\n",
       "      <td>85.097870</td>\n",
       "      <td>0.939882</td>\n",
       "      <td>-0.840</td>\n",
       "      <td>Thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>9</td>\n",
       "      <td>0.037589</td>\n",
       "      <td>0.318782</td>\n",
       "      <td>5.691042</td>\n",
       "      <td>0.002637</td>\n",
       "      <td>0.241715</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>-0.840</td>\n",
       "      <td>Thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>8</td>\n",
       "      <td>0.037337</td>\n",
       "      <td>0.306820</td>\n",
       "      <td>4.443999</td>\n",
       "      <td>0.002535</td>\n",
       "      <td>0.201485</td>\n",
       "      <td>57.444680</td>\n",
       "      <td>62.364731</td>\n",
       "      <td>0.585397</td>\n",
       "      <td>-0.343</td>\n",
       "      <td>Non_thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8</td>\n",
       "      <td>0.000803</td>\n",
       "      <td>0.290992</td>\n",
       "      <td>4.189402</td>\n",
       "      <td>0.003369</td>\n",
       "      <td>0.313858</td>\n",
       "      <td>39.795853</td>\n",
       "      <td>53.654439</td>\n",
       "      <td>0.592598</td>\n",
       "      <td>-0.866</td>\n",
       "      <td>Non_thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>0.002903</td>\n",
       "      <td>0.221407</td>\n",
       "      <td>2.410380</td>\n",
       "      <td>0.002089</td>\n",
       "      <td>0.055087</td>\n",
       "      <td>92.494078</td>\n",
       "      <td>64.243522</td>\n",
       "      <td>0.709552</td>\n",
       "      <td>-0.081</td>\n",
       "      <td>Thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>414</th>\n",
       "      <td>1</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.158765</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.001131</td>\n",
       "      <td>0.000055</td>\n",
       "      <td>92.780324</td>\n",
       "      <td>51.624957</td>\n",
       "      <td>1.094793</td>\n",
       "      <td>-0.854</td>\n",
       "      <td>Thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>415</th>\n",
       "      <td>1</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.180232</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000703</td>\n",
       "      <td>0.000250</td>\n",
       "      <td>110.996267</td>\n",
       "      <td>68.525570</td>\n",
       "      <td>0.992075</td>\n",
       "      <td>-0.844</td>\n",
       "      <td>Thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>416</th>\n",
       "      <td>2</td>\n",
       "      <td>0.004785</td>\n",
       "      <td>0.207217</td>\n",
       "      <td>1.835975</td>\n",
       "      <td>0.001749</td>\n",
       "      <td>0.003968</td>\n",
       "      <td>194.843373</td>\n",
       "      <td>131.003704</td>\n",
       "      <td>1.087150</td>\n",
       "      <td>1.390</td>\n",
       "      <td>Non_thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>417</th>\n",
       "      <td>1</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.180549</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000905</td>\n",
       "      <td>0.000852</td>\n",
       "      <td>95.014203</td>\n",
       "      <td>61.300038</td>\n",
       "      <td>1.003882</td>\n",
       "      <td>-0.378</td>\n",
       "      <td>Non_thrombosis</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>418</th>\n",
       "      <td>2</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.251139</td>\n",
       "      <td>1.416763</td>\n",
       "      <td>0.001014</td>\n",
       "      <td>0.138462</td>\n",
       "      <td>87.177818</td>\n",
       "      <td>61.182111</td>\n",
       "      <td>0.885760</td>\n",
       "      <td>0.062</td>\n",
       "      <td>Non_thrombosis</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>419 rows Ã— 11 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     dg        bt        cl     burts        pr      auth     areaSAS  \\\n",
       "0     2  0.000757  0.196523  1.996053  0.001401  0.046619   91.970392   \n",
       "1     9  0.037589  0.318782  5.691042  0.002637  0.241715    0.000000   \n",
       "2     8  0.037337  0.306820  4.443999  0.002535  0.201485   57.444680   \n",
       "3     8  0.000803  0.290992  4.189402  0.003369  0.313858   39.795853   \n",
       "4     4  0.002903  0.221407  2.410380  0.002089  0.055087   92.494078   \n",
       "..   ..       ...       ...       ...       ...       ...         ...   \n",
       "414   1  0.000000  0.158765  1.000000  0.001131  0.000055   92.780324   \n",
       "415   1  0.000000  0.180232  1.000000  0.000703  0.000250  110.996267   \n",
       "416   2  0.004785  0.207217  1.835975  0.001749  0.003968  194.843373   \n",
       "417   1  0.000000  0.180549  1.000000  0.000905  0.000852   95.014203   \n",
       "418   2  0.000000  0.251139  1.416763  0.001014  0.138462   87.177818   \n",
       "\n",
       "        areaSES   relSESA  consurf            type  \n",
       "0     85.097870  0.939882   -0.840      Thrombosis  \n",
       "1      0.000000  0.000000   -0.840      Thrombosis  \n",
       "2     62.364731  0.585397   -0.343  Non_thrombosis  \n",
       "3     53.654439  0.592598   -0.866  Non_thrombosis  \n",
       "4     64.243522  0.709552   -0.081      Thrombosis  \n",
       "..          ...       ...      ...             ...  \n",
       "414   51.624957  1.094793   -0.854      Thrombosis  \n",
       "415   68.525570  0.992075   -0.844      Thrombosis  \n",
       "416  131.003704  1.087150    1.390  Non_thrombosis  \n",
       "417   61.300038  1.003882   -0.378  Non_thrombosis  \n",
       "418   61.182111  0.885760    0.062  Non_thrombosis  \n",
       "\n",
       "[419 rows x 11 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "biodata = pd.read_csv('../../data/thrombosis_non_thrombosis_v4.csv', sep=\"\\t\")\n",
    "\n",
    "biodata.drop(['node'], axis=1, inplace=True)\n",
    "biodata"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>dg</th>\n",
       "      <th>bt</th>\n",
       "      <th>cl</th>\n",
       "      <th>burts</th>\n",
       "      <th>pr</th>\n",
       "      <th>auth</th>\n",
       "      <th>areaSAS</th>\n",
       "      <th>areaSES</th>\n",
       "      <th>relSESA</th>\n",
       "      <th>consurf</th>\n",
       "      <th>type</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>9</td>\n",
       "      <td>0.037589</td>\n",
       "      <td>0.318782</td>\n",
       "      <td>5.691042</td>\n",
       "      <td>0.002637</td>\n",
       "      <td>0.241715</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>-0.840</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>8</td>\n",
       "      <td>0.037337</td>\n",
       "      <td>0.306820</td>\n",
       "      <td>4.443999</td>\n",
       "      <td>0.002535</td>\n",
       "      <td>0.201485</td>\n",
       "      <td>57.444680</td>\n",
       "      <td>62.364731</td>\n",
       "      <td>0.585397</td>\n",
       "      <td>-0.343</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.180232</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000703</td>\n",
       "      <td>0.000250</td>\n",
       "      <td>110.996267</td>\n",
       "      <td>68.525570</td>\n",
       "      <td>0.992075</td>\n",
       "      <td>-0.844</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>0.004785</td>\n",
       "      <td>0.207217</td>\n",
       "      <td>1.835975</td>\n",
       "      <td>0.001749</td>\n",
       "      <td>0.003968</td>\n",
       "      <td>194.843373</td>\n",
       "      <td>131.003704</td>\n",
       "      <td>1.087150</td>\n",
       "      <td>1.390</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   dg        bt        cl     burts        pr      auth     areaSAS  \\\n",
       "0   9  0.037589  0.318782  5.691042  0.002637  0.241715    0.000000   \n",
       "1   8  0.037337  0.306820  4.443999  0.002535  0.201485   57.444680   \n",
       "2   1  0.000000  0.180232  1.000000  0.000703  0.000250  110.996267   \n",
       "3   2  0.004785  0.207217  1.835975  0.001749  0.003968  194.843373   \n",
       "\n",
       "      areaSES   relSESA  consurf  type  \n",
       "0    0.000000  0.000000   -0.840     1  \n",
       "1   62.364731  0.585397   -0.343     0  \n",
       "2   68.525570  0.992075   -0.844     1  \n",
       "3  131.003704  1.087150    1.390     0  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_idx = [1,2,415,416]\n",
    "#train_set = biodata.iloc[~biodata.index.isin(test_idx), 0:(biodata.shape[1]-1)]\n",
    "train_set = biodata.iloc[~biodata.index.isin(test_idx), :]\n",
    "#test_set = biodata.iloc[test_idx, 0:(biodata.shape[1]-1)]\n",
    "test_set = biodata.iloc[test_idx, :]\n",
    "\n",
    "x_train = train_set.iloc[:, 0:(biodata.shape[1]-1)]\n",
    "y_train = train_set.iloc[:, (biodata.shape[1]-1)]\n",
    "\n",
    "x_test = test_set.iloc[:, 0:(biodata.shape[1]-1)]\n",
    "y_test = test_set.iloc[:, (biodata.shape[1]-1)]\n",
    "\n",
    "y_test.replace(['Thrombosis', 'Non_thrombosis'],[1, 0], inplace=True)\n",
    "y_train.replace(['Thrombosis', 'Non_thrombosis'],[1, 0], inplace=True)\n",
    "\n",
    "test_set.reset_index(drop=True, inplace=True)\n",
    "train_set.reset_index(drop=True, inplace=True)\n",
    "y_train.reset_index(drop=True, inplace=True)\n",
    "y_test.reset_index(drop=True, inplace=True)\n",
    "x_train.reset_index(drop=True, inplace=True)\n",
    "x_test.reset_index(drop=True, inplace=True)\n",
    "test_set"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/rios/projects/thrombosis/src/classification/sfc.py:128: RuntimeWarning: invalid value encountered in long_scalars\n",
      "  acc_pos = tp / (tp + fp)\n"
     ]
    }
   ],
   "source": [
    "def runXGBoost(x_train, y_train, x_test, y_test, prob=False, metric = 'auc'):   \n",
    "\n",
    "    d_train = xgb.DMatrix(x_train, y_train)\n",
    "    d_test = xgb.DMatrix(x_test, y_test)\n",
    "\n",
    "    params = {'booster': 'gbtree',\n",
    "        'objective': \"binary:logistic\",\n",
    "        'nthread': 4,\n",
    "        'eval_metric': metric}\n",
    "\n",
    "    myfit = xgb.train(params = params,\n",
    "        dtrain = d_train,\n",
    "        num_boost_round = 100,\n",
    "        maximize = True)\n",
    "\n",
    "    return (myfit.predict(d_test))\n",
    "\n",
    "acc, f1, auc, pred = SynClass(x_train, y_train, x_test, y_test, learner = runXGBoost, scoring = 'auc', classThreshold = 0.5, probability = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0.38218614, 0.31720081, 0.33943908, 0.21270363])"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pred"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_search.py:306: UserWarning: The total space of parameters 8 is smaller than n_iter=50. Running 8 iterations. For exhaustive searches, use GridSearchCV.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 240 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  3.  5.  6.  4.  7.  7.  8.  6.  5.  8.\n  4.  8.  4.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  2.  6.  3.  4.\n  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.\n  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  4.  5.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  5.  8.  7.  4.  5.  7.  4.  7.  4.  5.  7.  9.  7.  9. 10.  6.  9.\n  9.  6.  8.  9.  8.  6.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.\n  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  8.  6.  7. 10.  5.  4.  7.  4.\n  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  8.  8.\n  8.  3.  1.  7.  5.  8.  9.  5.  2.  7.  5.  3.  3.  5.  8. 10.  6.  9.\n  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  6.  4.  7.  4.  5.  4.\n  6.  9.  8.  3.  3.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.\n  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7.\n 11.  8.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  2. 10.  5.  8.  9.  7.\n  5.  5.  4.  7. 10.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.\n  8.  8.  7.  6.  9.  7.  5.  7.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.\n  8.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  6.  1.  2.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  1.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  4.  3.  5.  2.  2.  5.  4.  4.  4.  6.  3.\n  3.  4.  4.  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.\n  7. 10. 10.  7.  8.  7.  9. 12.  8.  7.  2.  9.  5.  4.  5.  5. 11.  9.\n 10.  8.  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.\n  6. 11.  8.  8.  9.  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.\n  7.  5.  9.  7.  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  1.  3.  3.\n  3.  8.  6.  5.  5.  7. 10. 10.  4.  5.  4.  5.  9.  3.  5.  4.  6. 13.\n  5.  7.  8.  5.  6. 10.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.\n  4.  9.  9.  4. 12.  7.  3.  9.  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.\n  5.  2.  4.  5.  3.  3.  5.  8.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.\n  5.  7.  9.  8.  6.  4.  7.  4.  5.  6.  9.  5.  3.  2.  3.  4.  7.  4.\n  4.  4.  9.  7.  5.  4.  8.  5.  8.  5.  6.  3.  3.  2.  6.  9. 11.  7.\n  6. 10.  5.  3.  5.  9. 11.  8.  9.  9. 10.  7.  6.  3.  7.  8.  4.  6.\n 10. 10.  4.  4.  5.  5.  7.  4.  6.  5.  9.  8.  3.  4.  2.  3.  7.  8.\n  6.  7.  7. 11.  8.  9. 11.  7.  8.  6.  4.  9.  5.  2. 10.  5.  9.  7.\n  5.  5.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6.  7.  7. 10. 12.  8.\n  6.  7.  6.  9.  8.  7.  5.  4.  3.  3.  6.  2.  5.  2.  6.  4.  7.  5.\n  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11.  5.  6.  9.  5.  7.  6. 10.\n  9. 12.  8.  9.  6.  8.  6.  1.  3.  4.  4.  1.  2.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  9.  8.  5.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  4.  1.  4.  3.  3.  2.  5.  6. 10.  8.  6.  5.  7. 10.\n  7.  8.  7.  9. 12.  8. 10.  2.  9.  5.  4.  5.  5. 11.  8.  8.  9.  6.\n  9.  9. 11. 11.  5.  9.  7.  3.  6.  6. 11.  8.  8.  9.  9.  5.  7. 10.\n  8.  7.  4.  5.  7.  4.  4.  7.  7.  9.  7.  9. 10.  6.  9.  9.  6.  8.\n  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  7.  8.  5.  6.  7. 10.  4.  7.  4.  8.\n  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  3.\n  7.  9.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.  8. 10.\n 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.  9.\n  5.  8.  3.  2.  3.  4.  4.  4.  4.  9.  9.  7.  3.  4.  8.  5.  8.  7.\n  5.  6.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7. 11.  8.\n  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.\n  4.  6.  5.  9.  8.  4.  2.  5.  7.  8.  6.  7.  7. 11.  8.  9.  5.  8.\n  4.  7.  4.  8.  6.  6.  9.  4.  5.  2. 10.  5.  8.  5.  5.  4.  7.  7.\n  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.\n  6.  9.  8.  5.  7.  4.  3.  3.  6.  2.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11.  9.\n  8.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  2.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.\n  4.  2.  4.  1.  3.  2.  5.  8.  6.  6.  8.  6.  5.  7. 10. 10.  7.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5. 11.  9. 10.  8.  9. 11.  6.\n  9.  9. 11.  9. 11.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.  9.  9.\n  8.  9.  8.  6.  3.  2.  3.  3.  3.  8.  6.  5.  5.  7. 10. 10.  5.  4.\n  5.  9.  3.  7.  5.  6. 13.  5.  7.  8.  5.  7. 10.  5.  4.  7.  4.  8.\n  5.  8.  5.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.\n  8.  3.  1.  7.  9.  5.  8.  9.  5.  4.  7.  5.  3.  3.  5.  8. 10.  6.\n  9.  8.  8. 10. 10.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  4.\n  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  9.  9.  7.  5.  3.  4.  8.  5.\n  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6.  5.  3.  5.  9.  7. 11.\n  9.  9. 10.  7.  6.  3.  5.  4.  6. 10.  4.  4.  5.  5.  7.  4.  4.  6.\n  5.  9.  3.  4.  2.  3.  5.  6.  7. 11.  9. 11.  5.  8.  4.  7.  4.  8.\n  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7.  7. 10.\n  6.  4. 10.  6.  7.  4.  4. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.\n  9.  8.  7.  5.  7.  4.  3.  3.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  8.  6.  2.  3.  4.  4.  5.  2.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  8.  5.  4.  7.  3.  6.  7.  7.  8.  2.  5.  8.  4.  8.\n  4.  7.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.  4.  4.\n  2.  4.  1.  4.  3.  3.  2.  5.  8.  6. 10.  8.  7. 10. 10.  7.  8.  7.\n  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.  9.  9.\n 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  9.  9.  5.\n  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.\n 10. 10.  4.  5.  4.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7.\n 10.  5.  4.  7.  8.  8.  5.  3.  4.  2.  9.  9.  5.  4. 12.  7.  3.  9.\n  9.  8.  8.  8.  3.  1.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.\n 10.  6.  8.  8. 10. 10.  8.  5.  4. 14.  7.  9.  8.  6.  7.  5.  4.  5.\n  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.\n  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  7. 11.\n  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10.  4.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2.  5.  8.  9.  7.\n  5.  4.  7.  7. 10.  6. 10.  6.  7.  4.  4.  6. 12.  7.  7. 10.  8.  6.\n  8.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.\n  8.  3.  7.  8.  7. 10.  9.  9.  7. 11.  6.  9.  5.  7.  6. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  3.  3.  4.  1.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.\n  6.  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  5.  8.  6.  6. 10.  8.  6.\n  5.  7. 10. 10.  7.  7. 12.  8. 10.  7.  9.  5.  4.  5.  5. 11.  9. 10.\n  8.  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6.\n 11.  8.  8.  9.  9.  5.  7. 10.  8.  7.  4.  5.  4.  4.  7.  4.  7.  5.\n  7.  9.  9. 10.  6.  9.  9.  6.  8.  9.  8.  3.  2.  1.  3.  3.  3.  8.\n  6.  5.  5.  7. 10.  4.  5.  4.  5.  7.  5.  4.  6. 13.  5.  7.  8.  5.\n  6.  7. 10.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  4.  9.  5.  4.\n  7.  3.  9.  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.\n  3.  3.  5.  8. 10.  6.  9.  8.  8. 10. 10.  8.  6. 14.  5.  7.  9.  8.\n  4.  7.  4.  5.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.\n  9.  5.  3.  5.  8.  7.  6.  3.  3.  6.  9. 11.  9.  6. 10.  5.  3.  5.\n  9.  7.  8.  9. 10.  7.  3.  7.  5.  8.  4.  6. 10. 10.  4.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.\n  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5. 10.  5.  8.  9.  7.  5.\n  4.  7.  7. 10.  6.  4. 10.  6.  7.  6. 12.  7.  7.  7. 12.  8.  6.  8.\n  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  5.  2.  6.  6.  4.  7.  5.\n  8.  3.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  5.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  1.\n  3.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  8.  2.  6.  5.  8.  4.\n  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.  4.  4.\n  2.  4.  1.  4.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5. 10. 10.  7.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  9.  9.\n 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  7.  6.  6. 11.  8.  8.  9.  9.\n  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  7.  9. 10.\n  9.  9.  6.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7. 10.\n 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6.  5.  7.  5.  6.  7.  5.  4.\n  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5. 12.  7.  3.  9.\n  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  5.\n  8. 10.  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.\n  4.  7.  4.  5.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  9.  9.\n  7.  5.  3.  4.  8.  5.  8.  7.  5.  3.  3.  2. 11.  9.  7.  6. 10.  3.\n  5.  9.  7. 11.  8.  9.  9. 10.  6.  3.  7.  5.  8.  6. 10. 10.  4.  4.\n  5.  5.  7.  4.  4.  6.  5.  9.  8.  3.  2.  3.  5.  7.  8.  6.  7.  7.\n 11.  8.  9. 11.  5.  8.  4.  7.  4.  8.  6.  4.  9.  4.  5.  2. 10.  5.\n  8.  9.  7.  5.  5.  4.  7.  7. 10.  6.  4. 10.  7.  4.  4.  6. 12.  7.\n  7.  7. 10. 12.  8.  6.  8.  7.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.\n  2.  6.  4.  7.  5.  8.  3.  7.  8. 10. 10.  7. 11. 11.  5.  6.  9.  5.\n  7.  6. 11. 10.  9. 12.  8.  9.  8.  1.  2.  3.  4.  5.  1.  2.  3.  3.\n  4.  1.  3.  3.  2.  2.  3.  2.  2.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  4.  8.  4.  7.  3.  4.  2.  3.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.\n  3.  4.  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  7.  9. 12.  8. 10.  7.  2.  5.  4.  5.  5. 11.  9. 10.\n  8.  8.  9.  9. 11.  6.  9.  9.  9. 11.  5.  9.  3.  7.  6.  6. 11.  8.\n  8.  9.  9.  5.  7. 10.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.\n  6.  9.  6.  8.  6.  3.  2.  1.  3.  3.  8.  5.  7. 10. 10.  4.  5.  4.\n  5.  9.  3.  7.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  7.  4.\n  5.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.\n  8.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.\n  9.  8.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  7.  5.  3.  4.  8.  8.\n  7.  5.  6.  3.  3.  2.  6.  9.  9.  7.  6. 10.  5.  3.  9.  7. 11.  8.\n  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.\n  7.  5.  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.\n 10. 12.  8.  6.  8.  7.  6.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  6.\n  6.  7.  5.  3.  7.  8.  7. 10. 10.  9.  9. 11. 11.  5.  9.  5.  7.  6.\n 11. 10. 12.  9.  6.  8.  6.  1.  2.  3.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  3.  2.  2.  1.  3.  2.  7.  1.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  5.  4.  7.  3.  5.  4.  7.  7.  8.  2.  6.  5.  8.\n  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  2.  3.  3.  4.  4.\n  2.  4.  4.  3.  3.  2.  8.  6.  6. 10.  6.  5.  7. 10.  8.  7.  9. 12.\n 10.  7.  2.  9.  5.  5.  5.  9. 10.  8.  8.  9.  9. 11.  6.  9. 11.  9.\n 11.  5.  7.  3.  7.  6.  6. 11.  8.  8.  9.  5.  7. 10.  8.  7.  4.  5.\n  7.  4.  4.  7.  7.  5.  7.  9.  7.  9. 10.  6.  9.  9.  6.  8.  9.  8.\n  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7. 10.  4.  5.  4.  5.  9.\n  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  7.  4.  8.  5.\n  8.  3.  4.  2.  4.  9.  9.  5.  4. 12.  7.  9.  9.  8.  8.  8.  3.  1.\n  7.  9.  5.  9.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.  8.  8. 10.\n 10.  8.  5.  4.  6. 14.  5.  9.  8.  6.  4.  7.  4.  5.  4.  6.  9.  5.\n  8.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  5.  6.  3.  2.  6.  9. 11.  9.  7. 10.  5.  3.  5.  9.  7. 11.  8.  9.\n  9. 10.  7.  6.  7.  5.  8.  4. 10. 10.  4.  4.  5.  5.  7.  4.  4.  6.\n  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7.  8.  9. 11.  5.  8.  4.  4.\n  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7. 10.\n  6.  4. 10.  6.  4.  4.  6. 12.  7.  7.  7. 10. 12.  6.  8.  7.  6.  9.\n  8.  7.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.  7.\n  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7. 11. 10.  9. 12.  8.\n  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  4.  7.  5.  6.  4.  7.  8.  2.  6.  5.  8.  4.\n  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.\n  3.  4.  4.  2.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  9.  8. 10.  7.  2.  9.  5.  4.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  6.  9. 11.  9.  5.  9.  7.  3.  7.  8.  8.  9.  9.  7. 10.\n  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  6.  5.  7. 10. 10.  4.  5.\n  5.  9.  3.  7.  5.  4. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  4.  8.\n  5.  8.  5.  3.  4.  4.  2.  4.  9.  5.  4. 12.  3.  9.  9.  8.  8.  8.\n  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  8. 10.  6.  9.  8.\n  8. 10. 10.  8.  5.  4.  6.  5.  7.  8.  6.  4.  4.  5.  4.  6.  9.  5.\n  8.  3.  2.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  5.  9.  7. 11.  8.\n  9.  9.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  4.  4.\n  5.  9.  8.  3.  4.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.  8.\n  4.  7.  4.  6.  6.  4.  4.  5.  2. 10.  8.  9.  7.  5.  5.  4.  7.  7.\n 10.  6.  4.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.\n  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  5.  8.\n  3.  7.  8.  7. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  6. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  5.  6.  4.  7.  2.  5.  8.  8.  4.  7.\n  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.  4.  4.  2.\n  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5.  9. 10.  8.  8.  9.  9.\n 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5.  7. 10.  8.  7.  5.  7.  4.  4.  7.  4.  7.  5.  9.  7.  9. 10.\n  9.  9.  6.  8.  9.  8.  3.  2.  3.  3.  3.  8.  6.  5.  5.  7. 10. 10.\n  4.  5.  4.  5.  9.  7.  5.  4.  6. 13.  5.  7.  5.  7. 10.  5.  7.  4.\n  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5. 12.  7.  3.  9.  8.  8.\n  8.  3.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5. 10.  9.  8.\n  8. 10.  8.  5.  4.  6. 14.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.  9.\n  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.\n  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.\n  7. 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  6. 10. 10.  4.  4.  7.\n  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7. 10. 12.  8.\n  8.  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  6.  6.  4.  7.\n  5.  8.  7.  8. 10. 10.  9.  7. 11. 11.  5.  6.  5.  6. 11. 10.  9. 12.\n  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  1.  3.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  2.  5.  6.  6. 10.  8.  6.  5.\n  7. 10.  7.  8.  7.  9.  8.  7.  2.  9.  5.  5. 11.  9. 10.  8.  8.  9.\n  9. 11.  6.  9.  9. 11. 11.  5.  7.  3.  7.  6.  6.  8.  8.  9.  9.  7.\n 10.  8.  7.  4.  5.  7.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7. 10. 10.\n  4.  5.  4.  5.  9.  3.  7.  5.  6.  5.  7.  8.  5.  6.  7. 10.  5.  4.\n  7.  8.  5.  8.  5.  3.  4.  4.  2.  9.  9.  5.  4. 12.  7.  3.  9.  9.\n  8.  8.  8.  3.  1.  7.  9.  5.  9.  5.  4.  7.  5.  3.  3.  5.  8. 10.\n  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.\n  5.  4.  6.  9.  5.  8.  2.  3.  4.  7.  4.  4.  4.  9.  9.  5.  3.  4.\n  8.  5.  8.  5.  6.  3.  3.  2.  6.  9.  9.  6. 10.  5.  3.  5.  7.  8.\n  9.  9. 10.  7.  6.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.\n  4.  6.  5.  9.  8.  4.  2.  3.  7.  8.  6.  7.  7.  8.  9. 11.  5.  4.\n  7.  4.  8.  6.  6.  4.  9.  4.  5. 10.  5.  8.  9.  7.  5.  5.  4.  7.\n  7. 10.  6.  4. 10.  6.  7.  4.  4. 12.  7.  7.  7. 12.  8.  6.  8.  7.\n  6.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.  2.  6.  4.  7.  5.  8.  3.\n  7.  7. 10.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.  9. 12.  8.\n  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  3.\n  3.  4.  4.  2.  4.  1.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.\n  8.  8.  9.  9. 11.  6.  9.  9.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.\n  8.  9.  9.  5.  7.  7.  4.  7.  4.  4.  7.  4.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10.\n 10.  4.  5.  4.  5.  3.  7.  5.  4.  6. 13.  8.  5.  6.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  4.  4.  2.  4.  9.  9.  5.  4. 12.  9.  9.  8.\n  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8.\n  6.  9.  8. 10. 10.  8.  5.  4.  6.  5.  7.  9.  6.  4.  7.  4.  5.  4.\n  5.  8.  3.  2.  3.  4.  4.  4.  4.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  5.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  9. 11.  8.  9.  9.\n 10.  7.  6.  3.  7.  5.  8.  4.  6. 10.  4.  4.  5.  5.  7.  4.  6.  8.\n  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.  8.  4.  7.\n  4.  8.  6.  6.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7.  7.\n 10.  6.  4. 10.  6.  7.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  2.  2.  1.  3.  2.  7.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 8.  4.  4.  8.  5.  4.  7.  3.  6.  7.  7.  8.  2.  6.  5.  8.  4.  8.\n  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.  4.\n  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.\n  7.  8.  9. 12.  8. 10.  7.  9.  5.  4.  5. 11.  9. 10.  8.  8.  9.  9.\n 11.  6.  9.  9. 11.  9.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  9.\n  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  4.  7.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  8.  8.  6.  2.  1.  3.  3.  3.  8.  5.  5.  7. 10. 10.\n  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.\n  4.  7.  4.  5.  5.  3.  4.  4.  2.  4.  9.  4. 12.  7.  3.  9.  9.  8.\n  8.  3.  1.  9.  5.  8.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.\n  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.\n  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.\n  4.  5.  8.  7.  5.  6.  3.  3.  6.  9. 11.  9.  7.  6.  5.  3.  5.  9.\n  7. 11.  8.  9. 10.  7.  6.  3.  7.  5.  8.  4. 10. 10.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  4.  5.  2. 10.  5.  8.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10.\n 12.  6.  8.  7.  6.  9.  8.  7.  7.  4.  3.  3.  6.  5.  2.  6.  6.  4.\n  7.  5.  8.  3.  8.  7. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6.\n 11. 10.  9. 12.  8.  9.  8.  6.  1.  2.  3.  4.  2.  3.  4.  1.  3.  3.\n  2.  2.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  6.  5.\n  8.  4.  8.  4.  7.  3.  4.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  4.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.\n  7. 10. 10.  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.\n  9. 10.  8.  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  7.  6.\n 11.  8.  8.  9.  9.  5. 10.  8.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.\n  9.  7.  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.\n  8.  6.  5.  5. 10. 10.  4.  5.  4.  9.  3.  5.  4. 13.  5.  7.  8.  5.\n  6.  7.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  2.  4.  9.  9.  5.  4.\n 12.  7.  3.  9.  9.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  5.\n  5.  8. 10.  6.  9.  8.  8. 10. 10.  5.  4.  6. 14.  5.  7.  9.  8.  6.\n  4.  7.  4.  5.  4.  6.  9.  5.  3.  2.  7.  4.  4.  9.  9.  7.  3.  4.\n  8.  5.  8.  7.  5.  6.  3.  2.  6. 11.  9.  7.  6. 10.  5.  3.  5.  9.\n  7. 11.  8.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.\n  5.  7.  4.  4.  6.  5.  9.  8.  3.  4.  3.  5.  7.  8.  6.  7. 11.  8.\n  9. 11.  5.  8.  7.  4.  8.  6.  6.  4.  9.  5.  2.  8.  9.  7.  5.  5.\n  4.  7.  7. 10.  6.  4.  7.  4.  4.  6. 12.  7.  7.  7. 10.  8.  6.  8.\n  7.  6.  9.  7.  5.  4.  3.  3.  2.  5.  2.  6.  4.  7.  5.  8.  3.  7.\n  8.  7. 10. 10.  9.  9.  7. 11. 11.  6.  9.  5.  7.  6. 11. 10.  9. 12.\n  8.  9.  6.  8.  6.  1.  3.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  8.  4.  7.  3.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  1.  4.  3.  3.  2.  5.  8.  6. 10.  6.  5.  7. 10.\n 10.  7.  8.  7.  9. 12.  8. 10.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.\n  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  3.  6.  6. 11.  8.  8.\n  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.\n  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  1.  3.  3.  3.  6.  5.  7.\n 10. 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  6.  7.\n 10.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4.\n 12.  7.  3.  9.  9.  8.  8.  8.  3.  1.  7.  5.  8.  9.  5.  2.  4.  7.\n  5.  3.  3.  8. 10.  6.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.\n  8.  6.  4.  7.  4.  5.  4.  6.  9.  5.  8.  3.  3.  4.  7.  4.  4.  9.\n  9.  7.  5.  3.  4.  8.  5.  8.  7.  5.  6.  3.  2.  6.  9. 11.  9.  7.\n  6. 10.  5.  3.  5.  9.  7. 11.  8.  9.  9. 10.  7.  3.  7.  5.  4.  6.\n 10. 10.  4.  5.  5.  7.  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.\n  8.  6.  7. 11.  8.  8.  4.  7.  4.  8.  6.  4.  9.  4.  2. 10.  5.  9.\n  7.  5.  5.  4.  7.  7. 10.  6. 10.  6.  4.  4.  6. 12.  7.  7.  7. 10.\n 12.  8.  6.  8.  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  2.  6.\n  6.  4.  7.  5.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  9.  7.\n  6. 10.  9. 12.  8.  9.  6.  8.  1.  2.  4.  4.  5.  1.  3.  3.  4.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  8.  4.  8.  4.  7.  3.  4.  2.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  4.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6. 10. 10.  7.\n  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5.  7. 10.  8.  7.  4.  5.  4.  4.  7.  7.  5.  7.  9.  9. 10.  6.\n  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7.\n 10. 10.  5.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6. 10.  5.\n  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.\n  3.  9.  9.  8.  8.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  3.  3.  5.\n  8. 10.  6.  9.  8.  8. 10.  8.  4.  6. 14.  5.  9.  8.  4.  7.  4.  5.\n  4.  6.  9.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  7.  5.  3.  4.  8.\n  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7. 10.  3.  5.  9.  7. 11.\n  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10.  4.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.\n  9. 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.\n  9.  7.  5.  4.  7.  7.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7.\n 10. 12.  8.  6.  6.  9.  8.  5.  7.  4.  3.  6.  2.  5.  2.  6.  6.  4.\n  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6.\n 11. 10.  9. 12.  8.  9.  6.  6.  2.  3.  4.  4.  5.  1.  2.  3.  4.  1.\n  3.  3.  2.  1.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  6.\n  3.  4.  4.  2.  4.  1.  4.  3.  3.  5.  8.  6.  6.  8.  5.  7. 10.  7.\n  8.  7. 12. 10.  7.  2.  5.  4.  5. 11.  9.  9.  9. 11.  6.  9.  9. 11.\n  9. 11.  9.  7.  3.  7.  6. 11.  8.  8.  9.  9.  5.  7. 10.  8.  7.  4.\n  5.  7.  4.  4.  7.  4.  7.  7.  9.  7.  9. 10.  6.  9.  9.  8.  9.  6.\n  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.  5.  4.  5.  9.  3.\n  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  7.  4.  8.  5.\n  8.  5.  3.  4.  4.  4.  9.  9.  5.  4.  7.  3.  9.  9.  8.  8.  8.  3.\n  1.  7.  9.  8.  9.  5.  2.  7.  5.  3.  3.  5.  8. 10.  6.  9.  8. 10.\n 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  5.  4.  6.  9.  5.  8.\n  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7. 11.  9.\n  9. 10.  7.  6.  3.  8.  4.  6. 10. 10.  4.  4.  5.  5.  4.  4.  6.  5.\n  9.  8.  3.  4.  2.  5.  7.  6.  7.  7. 11.  9. 11.  5.  8.  4.  7.  4.\n  8.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7. 10.  4.\n 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.  9.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.\n  1.  3.  3.  2.  2.  1.  3.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  4.  9.  8.  5.  4.  7.  3.  5.  4.  7.  8.  2.  6.  5.  8.  4.  4.\n  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.  4.\n  4.  2.  4.  1.  4.  2.  5.  8.  6. 10.  8.  6.  5.  7. 10. 10.  7.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11. 10.  8.  8. 11.  6.\n  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  7.  4.  7.  5.  7.  7.  9.  6.  9.  9.  6.\n  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  7. 10.  4.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  4.\n  8.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.\n  8.  8.  3.  1.  7.  9.  5.  8.  9.  2.  4.  7.  5.  3.  3.  5.  8. 10.\n  6.  9.  8.  8. 10. 10.  8.  5.  4. 14.  5.  7.  9.  8.  6.  4.  7.  4.\n  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  9.  9.  7.  5.  8.  5.  7.\n  5.  6.  3.  3.  2.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7. 11.  8.\n  9.  9.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.\n  5.  8.  4.  7.  4.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  5.  4.\n  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7. 10. 12.  8.  6.  8.\n  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.\n  5.  8.  3.  7.  8.  7. 10. 10.  9.  9. 11. 11.  5.  6.  9.  5.  7.  6.\n 11. 10. 12.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  3.  2.  2.  1.  2.  7.  1.  2.  1.  2.  2.  1.  1.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  3.  4.  2.  3.  2.  2.  5.  4.  2.  6.  3.  3.  4.  2.  4.\n  1.  4.  3.  3.  2.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  7.  8.  7.\n  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.  9.  9.\n  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10.  4.  4.\n  5.  9.  3.  7.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  7.  4.\n  8.  5.  8.  3.  4.  2.  4.  9.  5.  4. 12.  7.  3.  9.  8.  8.  8.  3.\n  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.\n  8.  8. 10. 10.  8.  5.  6. 14.  5.  7.  8.  6.  4.  7.  4.  5.  4.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.\n  5.  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  7.  6. 10.  5.  5.  9.  7.\n 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.\n  5.  7.  4.  4.  5.  9.  3.  4.  2.  3.  5.  8.  7.  7. 11.  8.  9. 11.\n  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.\n  5.  5.  7.  7. 10.  6.  4. 10.  6.  7.  4.  6.  7.  7.  7. 10. 12.  8.\n  6.  8.  7.  6.  9.  8.  7.  5.  7.  3.  3.  6.  2.  5.  2.  6.  6.  7.\n  5.  8.  3.  7.  8.  7. 10. 10.  9.  9.  7.  5.  6.  9.  5.  7.  6. 11.\n  9.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  1.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  2.  6.  3.\n  3.  4.  4.  2.  4.  1.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  9. 12.  8. 10.  7.  2.  9.  4.  5.  5. 11. 10.  8.  8.\n  9.  9. 11.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.\n  7.  9. 10.  6.  9.  9.  6.  8.  6.  3.  1.  3.  3.  3.  8.  6.  5.  5.\n  7. 10. 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.\n  6.  7.  5.  4.  7.  4.  5.  8.  3.  4.  4.  2.  5.  4. 12.  7.  3.  9.\n  9.  8.  8.  3.  1.  7.  9.  5.  9.  5.  4.  7.  3.  3.  5.  8. 10.  6.\n  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  9.  6.  4.  7.  4.  5.  4.\n  6.  9.  5.  8.  3.  3.  4.  4.  4.  9.  9.  7.  5.  3.  8.  5.  8.  7.\n  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9. 11.  9.\n 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8. 11.  5.\n  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10.\n  6.  7.  9.  8.  5.  7.  4.  3.  3.  2.  5.  2.  6.  6.  4.  7.  5.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7. 11. 10.  9.\n 12.  8.  6.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  4.  1.  3.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  8.  4.  7.  3.  5.  6.  4.  7.  8.  2.  5.  8.  4.  8.\n  7.  3.  4.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.  4.  2.\n  4.  1.  4.  3.  2.  5.  8.  6. 10.  8.  6.  5. 10. 10.  7.  8.  7.  9.\n 12.  8. 10.  7.  2.  9.  5.  5.  5. 11.  9. 10.  8.  8.  9.  9. 11.  6.\n  9.  9. 11.  9. 11.  5.  9.  7.  3.  6.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  7.  9.  9. 10.  6.  9.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  7. 10.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6. 10.  5.  4.  7.  4.\n  8.  5.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  8.  8.\n  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5. 10.  6.  9.\n  8.  8. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.\n  6.  9.  5.  8.  3.  2.  3.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.\n  5.  8.  7.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.\n  7. 11.  8.  9.  9.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  7.\n  4.  4.  6.  5.  9.  8.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  4.  2. 10.  5.  8.  7.  5.  5.\n  7.  7. 10.  6.  4. 10.  6.  7.  4.  4. 12.  7.  7. 10. 12.  8.  6.  8.\n  7.  6.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.\n  8.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 10.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  2.  2.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 8.  4.  9.  8.  5.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.  4.  8.\n  4.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.  4.  2.\n  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  7.\n  7. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.  9.  9.\n 11.  6.  9. 11. 11.  5.  9.  7.  3.  7.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  7.  9. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.\n  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  8.  5.  6.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4.  7.  3.  9.\n  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.\n  5.  8. 10.  6.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.\n  7.  4.  5.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  9.  9.  7.\n  5.  3.  4.  5.  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  6. 10.  5.\n  5.  9.  7. 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4. 10.  4.  4.\n  5.  4.  4.  6.  5.  9.  3.  4.  2.  5.  7. 11.  8.  9. 11.  8.  4.  7.\n  4.  8.  6.  6.  4.  9.  4.  5.  2.  5.  8.  9.  7.  5.  4.  7.  7.  6.\n  4.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.  9.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9. 11.  5.  9.  5.  7.  6. 11. 10.  9. 12.  8.\n  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  2.  3.  3.  4.  1.  3.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  8.  4.  7.  3.  4.  2.  3.  2.  2.  5.  5.  4.  4.  4.  6.  3.\n  3.  4.  2.  4.  1.  4.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10.\n 10.  7.  8.  7.  9. 12.  8. 10.  2.  9.  5.  4.  5.  5.  9. 10.  8.  9.\n  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  4.  7.  5.  7.  9.  7.\n  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.\n  5.  7. 10. 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.\n  5.  6.  7. 10.  5.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.\n  5.  4. 12.  7.  3.  9.  9.  8.  8.  8.  3.  1.  9.  5.  8.  9.  5.  2.\n  5.  3.  3.  5.  8. 10.  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.\n  7.  9.  8.  4.  4.  5.  4.  6.  5.  8.  2.  3.  4.  7.  4.  4.  9.  7.\n  5.  3.  4.  8.  5.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.\n  3.  5.  9.  7. 11.  8.  9.  9. 10.  7.  6.  7.  5.  8.  4.  6. 10. 10.\n  4.  4.  5.  5.  7.  4.  6.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.\n  7. 11.  9. 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.\n  5.  8.  9.  5.  5.  4.  7. 10.  6. 10.  6.  4.  4.  6. 12.  7.  7.  7.\n 10. 12.  8.  6.  8.  7.  6.  8.  7.  7.  4.  3.  3.  6.  2.  5.  6.  6.\n  4.  7.  5.  8.  3.  7.  8.  7. 10. 10.  9.  7. 11. 11.  5.  6.  9.  5.\n  6. 11. 10.  9. 12.  8.  9.  6.  8.  1.  3.  4.  4.  5.  1.  3.  4.  1.\n  3.  2.  1.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  5.  6.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  5.  2.  5.  5.  4.  4.  4.  2.  6.  4.  4.\n  2.  4.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  7.\n  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  6.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  5.  7. 10.  8.  7.  7.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.\n  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  6.  5.  5.  7. 10.\n 10.  4.  5.  5.  9.  3.  7.  5.  4.  6.  5.  7.  8.  6.  7. 10.  5.  4.\n  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  4. 12.  7.  3.  9.  9.\n  8.  8.  8.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8.\n 10.  6.  9.  8. 10. 10.  8.  5.  5.  7.  9.  8.  6.  4.  7.  4.  5.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  4.  8.  5.\n  8.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7.\n 11.  8.  9.  9. 10.  7.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.\n  7.  4.  6.  5.  9.  8.  3.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  4.  9.  5.  2. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 12.\n  8.  6.  8.  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.\n  6.  7.  5.  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11.  5.  6.  9.  7.\n  6. 11. 10.  9.  8.  9.  8.  6.  1.  2.  3.  4.  5.  1.  2.  3.  3.  4.\n  3.  3.  2.  2.  1.  3.  7.  1.  2.  1.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  6.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  2.  3.  3.\n  4.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  6.  5.  7. 10. 10.  8.\n  7.  9.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9.  8.  8.  9.  9. 11.\n  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  5.\n  7. 10.  8.  4.  5.  7.  4.  4.  7.  4.  5.  7.  9.  7.  6.  9.  6.  8.\n  9.  8.  2.  3.  3.  3.  8.  6.  5.  5.  7. 10.  4.  5.  4.  5.  9.  3.\n  7.  5.  4.  6. 13.  7.  8.  5.  6.  7. 10.  5.  4.  7.  8.  5.  8.  5.\n  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.  8.  3.\n  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8.  6.  9.  8.\n  8. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  3.  4.  8.  5.\n  8.  7.  5.  6.  3.  2.  6. 11.  7.  6. 10.  5.  3.  5.  9.  7. 11.  8.\n  9.  9. 10.  7.  6.  3.  7.  5.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.\n  4.  5.  9.  8.  3.  4.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.\n  8.  4.  7.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  4.\n  7.  7. 10.  6.  4. 10.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.\n  8.  7.  6.  9.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  4.  7.  5.\n  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  6.  5.  7.  6. 11.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  5.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  2.  6.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  2.  8.  6.  6. 10.  8.  6.  5.\n  7.  7.  8.  7.  9. 12.  8.  7.  9.  5.  4.  5. 11.  9. 10.  8.  8.  9.\n  9. 11.  6.  9.  9. 11.  9. 11.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9.\n 10.  6.  9.  9.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7.\n 10. 10.  4.  4.  3.  7.  5.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  3.  4.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.\n  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.\n  8. 10.  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.\n  4.  7.  4.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.\n  7.  5.  3.  4.  8.  5.  8.  7.  5.  6.  3.  2.  6.  9. 11.  9.  7.  6.\n  5.  3.  9.  7. 11.  8.  9. 10.  7.  6.  3.  5.  8.  4.  6. 10. 10.  4.\n  5.  5.  7.  4.  4.  6.  5.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7.\n 11.  8.  9.  5.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  9.  7.\n  5.  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  6. 12.  7.  7.  7. 10.\n 12.  8.  6.  8.  7.  6.  9.  8.  7.  5.  7.  3.  3.  6.  5.  2.  6.  6.\n  4.  7.  5.  8.  3.  7.  8.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11.\n 10.  9. 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.\n  1.  3.  3.  2.  2.  1.  3.  2.  2.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.\n  6.  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  5.  8.  6.  8.  5.  7. 10.\n 10.  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5. 11.  9. 10.  8.\n  9. 11.  6.  9.  9. 11.  9.  5.  9.  7.  7.  6. 11.  9.  9.  5.  7. 10.\n  7.  4.  5.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  9.  9.  6.  8.\n  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  7. 10. 10.  4.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  5.  6.  7. 10.  4.  7.  4.  8.\n  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.\n  8.  3.  7.  9.  8.  5.  2.  4.  7.  5.  3.  3.  8. 10.  6.  9.  8.  8.\n 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  5.  4.  9.  3.\n  2.  3.  4.  7.  4.  4.  4.  9.  5.  3.  4.  8.  5.  8.  7.  5.  6.  3.\n  3.  9. 11.  9.  7.  6. 10.  5.  3.  5.  7.  8.  9.  9. 10.  7.  6.  3.\n  7.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.  4.  6.  5.  9.  8.  3.\n  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.  8.  4.  7.  4.\n  8.  6.  4.  9.  4.  5.  2. 10.  8.  9.  7.  5.  5.  4.  7.  7. 10.  4.\n 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.  9.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  2.  6.  6.  4.  7.  5.  8.  3.  8.\n  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.  9. 12.\n  8.  9.  6.  8.  6.  1.  2.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  8.  2.  6.  5.\n  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.\n  4.  4.  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  7.  9. 12. 10.  7.  2.  5.  4.  5.  5. 11.  9. 10.  8.\n  8.  9. 11.  6.  9.  9. 11.  9. 11.  5.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5.  7.  8.  7.  4.  5.  7.  4.  4.  7.  7.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7.\n 10. 10.  4.  5.  4.  5.  9.  4.  6. 13.  5.  7.  8.  5.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  4.  2.  4.  9.  9.  5. 12.  7.  9.  9.  8.  8.\n  8.  3.  1.  7.  9.  5.  8.  9.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.\n  9.  8.  8. 10. 10.  4.  6. 14.  7.  9.  8.  6.  7.  4.  5.  4.  6.  9.\n  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.\n  8.  7.  5.  6.  3.  3.  2.  6.  9.  9.  7. 10.  5.  3.  5.  9.  7. 11.\n  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  6. 10.  4.  5.  5.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7.  8.  9. 11.  5.\n  8.  4.  7.  4.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.\n  4.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7. 10. 12.  8.  8.  7.\n  6.  9.  8.  7.  5.  4.  3.  3.  6.  2.  5.  2.  6.  4.  7.  5.  8.  3.\n  7.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.\n  3.  4.  2.  4.  1.  4.  3.  3.  2.  5.  6.  6. 10.  8.  6.  7. 10. 10.\n  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.\n  8.  9.  9.  6.  9.  9.  9. 11.  5.  9.  7.  3.  7.  6.  6.  8.  8.  9.\n  9.  7. 10.  8.  7.  4.  5.  7.  4.  7.  4.  7.  5.  9.  7.  9. 10.  6.\n  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  5.  5. 10. 10.\n  4.  5.  4.  5.  9.  3.  7.  5.  4. 13.  5.  7.  8.  5.  6.  7. 10.  5.\n  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  3.\n  9.  8.  8.  3.  1.  7.  5.  8.  9.  5.  2.  4.  7.  5.  5.  8. 10.  9.\n  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  8.  6.  4.  7.  4.  5.  4.\n  6.  9.  5.  8.  3.  2.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.\n  8.  7.  5.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7.\n 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.\n  5.  7.  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  7.  8.  6.  7. 11.  8.\n  9. 11.  5.  8.  4.  4.  8.  6.  6.  9.  4.  5. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  6.  7.  7.  7. 10. 12.  8.\n  6.  8.  6.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.  2.  6.  6.  4.  8.\n  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11.\n 10.  9. 12.  9.  6.  8.  6.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  3.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb Cell 5\u001b[0m in \u001b[0;36m<cell line: 21>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=15'>16</a>\u001b[0m         y_pred \u001b[39m=\u001b[39m model_cv\u001b[39m.\u001b[39mpredict(X_test)\n\u001b[1;32m     <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=17'>18</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m y_pred\n\u001b[0;32m---> <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=20'>21</a>\u001b[0m acc, f1, auc, pred \u001b[39m=\u001b[39m SynClass(x_train, y_train, x_test, y_test, learner \u001b[39m=\u001b[39;49m RSDT, scoring \u001b[39m=\u001b[39;49m \u001b[39m'\u001b[39;49m\u001b[39mauc\u001b[39;49m\u001b[39m'\u001b[39;49m, classThreshold \u001b[39m=\u001b[39;49m \u001b[39m0.5\u001b[39;49m, probability \u001b[39m=\u001b[39;49m \u001b[39mFalse\u001b[39;49;00m)\n",
      "File \u001b[0;32m~/projects/thrombosis/src/classification/sfc.py:190\u001b[0m, in \u001b[0;36mSynClass\u001b[0;34m(x_train, y_train, x_test, y_test, learner, scoring, classThreshold, probability)\u001b[0m\n\u001b[1;32m    188\u001b[0m \u001b[39m#fitting a model per attribute\u001b[39;00m\n\u001b[1;32m    189\u001b[0m \u001b[39mfor\u001b[39;00m att \u001b[39min\u001b[39;00m np\u001b[39m.\u001b[39marange(x_train\u001b[39m.\u001b[39mshape[\u001b[39m1\u001b[39m]):\n\u001b[0;32m--> 190\u001b[0m     result_by_att[:, att] \u001b[39m=\u001b[39m learner(x_train\u001b[39m.\u001b[39;49miloc[:, att], y_train, x_test\u001b[39m.\u001b[39;49miloc[:, att], y_test, prob\u001b[39m=\u001b[39;49mprobability, metric \u001b[39m=\u001b[39;49m scoring)\n\u001b[1;32m    192\u001b[0m statistical_weights \u001b[39m=\u001b[39m get_statistical_weights(x_train, y_train)\n\u001b[1;32m    193\u001b[0m prediction \u001b[39m=\u001b[39m np\u001b[39m.\u001b[39mapply_along_axis(weighted_mean, \u001b[39m1\u001b[39m, result_by_att, w \u001b[39m=\u001b[39m statistical_weights)\n",
      "\u001b[1;32m/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb Cell 5\u001b[0m in \u001b[0;36mRSDT\u001b[0;34m(X_train, y_train, X_test, y_test, prob, metric)\u001b[0m\n\u001b[1;32m      <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=7'>8</a>\u001b[0m model \u001b[39m=\u001b[39m DecisionTreeClassifier()\n\u001b[1;32m      <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=8'>9</a>\u001b[0m model_cv \u001b[39m=\u001b[39m RandomizedSearchCV(model, params, cv \u001b[39m=\u001b[39m cv, scoring\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mf1_macro\u001b[39m\u001b[39m'\u001b[39m, n_jobs \u001b[39m=\u001b[39m \u001b[39m-\u001b[39m\u001b[39m1\u001b[39m, n_iter\u001b[39m=\u001b[39m\u001b[39m50\u001b[39m)\n\u001b[0;32m---> <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=10'>11</a>\u001b[0m model_cv\u001b[39m.\u001b[39;49mfit(X_train, y_train)\n\u001b[1;32m     <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=12'>13</a>\u001b[0m \u001b[39mif\u001b[39;00m prob:\n\u001b[1;32m     <a href='vscode-notebook-cell:/home/rios/projects/thrombosis/src/classification/Testing_SFC.ipynb#ch0000054?line=13'>14</a>\u001b[0m     y_pred \u001b[39m=\u001b[39m model_cv\u001b[39m.\u001b[39mpredict_proba(X_test)\n",
      "File \u001b[0;32m~/.local/lib/python3.8/site-packages/sklearn/model_selection/_search.py:875\u001b[0m, in \u001b[0;36mBaseSearchCV.fit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    869\u001b[0m     results \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_format_results(\n\u001b[1;32m    870\u001b[0m         all_candidate_params, n_splits, all_out, all_more_results\n\u001b[1;32m    871\u001b[0m     )\n\u001b[1;32m    873\u001b[0m     \u001b[39mreturn\u001b[39;00m results\n\u001b[0;32m--> 875\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_run_search(evaluate_candidates)\n\u001b[1;32m    877\u001b[0m \u001b[39m# multimetric is determined here because in the case of a callable\u001b[39;00m\n\u001b[1;32m    878\u001b[0m \u001b[39m# self.scoring the return type is only known after calling\u001b[39;00m\n\u001b[1;32m    879\u001b[0m first_test_score \u001b[39m=\u001b[39m all_out[\u001b[39m0\u001b[39m][\u001b[39m\"\u001b[39m\u001b[39mtest_scores\u001b[39m\u001b[39m\"\u001b[39m]\n",
      "File \u001b[0;32m~/.local/lib/python3.8/site-packages/sklearn/model_selection/_search.py:1749\u001b[0m, in \u001b[0;36mRandomizedSearchCV._run_search\u001b[0;34m(self, evaluate_candidates)\u001b[0m\n\u001b[1;32m   1747\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_run_search\u001b[39m(\u001b[39mself\u001b[39m, evaluate_candidates):\n\u001b[1;32m   1748\u001b[0m     \u001b[39m\"\"\"Search n_iter candidates from param_distributions\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1749\u001b[0m     evaluate_candidates(\n\u001b[1;32m   1750\u001b[0m         ParameterSampler(\n\u001b[1;32m   1751\u001b[0m             \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mparam_distributions, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mn_iter, random_state\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mrandom_state\n\u001b[1;32m   1752\u001b[0m         )\n\u001b[1;32m   1753\u001b[0m     )\n",
      "File \u001b[0;32m~/.local/lib/python3.8/site-packages/sklearn/model_selection/_search.py:852\u001b[0m, in \u001b[0;36mBaseSearchCV.fit.<locals>.evaluate_candidates\u001b[0;34m(candidate_params, cv, more_results)\u001b[0m\n\u001b[1;32m    845\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mlen\u001b[39m(out) \u001b[39m!=\u001b[39m n_candidates \u001b[39m*\u001b[39m n_splits:\n\u001b[1;32m    846\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[1;32m    847\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mcv.split and cv.get_n_splits returned \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    848\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39minconsistent results. Expected \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    849\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39msplits, got \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(n_splits, \u001b[39mlen\u001b[39m(out) \u001b[39m/\u001b[39m\u001b[39m/\u001b[39m n_candidates)\n\u001b[1;32m    850\u001b[0m     )\n\u001b[0;32m--> 852\u001b[0m _warn_or_raise_about_fit_failures(out, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49merror_score)\n\u001b[1;32m    854\u001b[0m \u001b[39m# For callable self.scoring, the return type is only know after\u001b[39;00m\n\u001b[1;32m    855\u001b[0m \u001b[39m# calling. If the return type is a dictionary, the error scores\u001b[39;00m\n\u001b[1;32m    856\u001b[0m \u001b[39m# can now be inserted with the correct key. The type checking\u001b[39;00m\n\u001b[1;32m    857\u001b[0m \u001b[39m# of out will be done in `_insert_error_scores`.\u001b[39;00m\n\u001b[1;32m    858\u001b[0m \u001b[39mif\u001b[39;00m callable(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mscoring):\n",
      "File \u001b[0;32m~/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:367\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[0;34m(results, error_score)\u001b[0m\n\u001b[1;32m    360\u001b[0m \u001b[39mif\u001b[39;00m num_failed_fits \u001b[39m==\u001b[39m num_fits:\n\u001b[1;32m    361\u001b[0m     all_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[1;32m    362\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39mAll the \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    363\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mIt is very likely that your model is misconfigured.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    364\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mYou can try to debug the error by setting error_score=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mraise\u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    365\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    366\u001b[0m     )\n\u001b[0;32m--> 367\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[1;32m    369\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    370\u001b[0m     some_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[1;32m    371\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mnum_failed_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed out of a total of \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    372\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mThe score on these train-test partitions for these parameters\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    376\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    377\u001b[0m     )\n",
      "\u001b[0;31mValueError\u001b[0m: \nAll the 240 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  3.  5.  6.  4.  7.  7.  8.  6.  5.  8.\n  4.  8.  4.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  2.  6.  3.  4.\n  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.\n  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  4.  5.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  5.  8.  7.  4.  5.  7.  4.  7.  4.  5.  7.  9.  7.  9. 10.  6.  9.\n  9.  6.  8.  9.  8.  6.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.\n  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  8.  6.  7. 10.  5.  4.  7.  4.\n  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  8.  8.\n  8.  3.  1.  7.  5.  8.  9.  5.  2.  7.  5.  3.  3.  5.  8. 10.  6.  9.\n  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  6.  4.  7.  4.  5.  4.\n  6.  9.  8.  3.  3.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.\n  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7.\n 11.  8.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  2. 10.  5.  8.  9.  7.\n  5.  5.  4.  7. 10.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.\n  8.  8.  7.  6.  9.  7.  5.  7.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.\n  8.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  6.  1.  2.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  1.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  4.  3.  5.  2.  2.  5.  4.  4.  4.  6.  3.\n  3.  4.  4.  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.\n  7. 10. 10.  7.  8.  7.  9. 12.  8.  7.  2.  9.  5.  4.  5.  5. 11.  9.\n 10.  8.  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.\n  6. 11.  8.  8.  9.  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.\n  7.  5.  9.  7.  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  1.  3.  3.\n  3.  8.  6.  5.  5.  7. 10. 10.  4.  5.  4.  5.  9.  3.  5.  4.  6. 13.\n  5.  7.  8.  5.  6. 10.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.\n  4.  9.  9.  4. 12.  7.  3.  9.  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.\n  5.  2.  4.  5.  3.  3.  5.  8.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.\n  5.  7.  9.  8.  6.  4.  7.  4.  5.  6.  9.  5.  3.  2.  3.  4.  7.  4.\n  4.  4.  9.  7.  5.  4.  8.  5.  8.  5.  6.  3.  3.  2.  6.  9. 11.  7.\n  6. 10.  5.  3.  5.  9. 11.  8.  9.  9. 10.  7.  6.  3.  7.  8.  4.  6.\n 10. 10.  4.  4.  5.  5.  7.  4.  6.  5.  9.  8.  3.  4.  2.  3.  7.  8.\n  6.  7.  7. 11.  8.  9. 11.  7.  8.  6.  4.  9.  5.  2. 10.  5.  9.  7.\n  5.  5.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6.  7.  7. 10. 12.  8.\n  6.  7.  6.  9.  8.  7.  5.  4.  3.  3.  6.  2.  5.  2.  6.  4.  7.  5.\n  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11.  5.  6.  9.  5.  7.  6. 10.\n  9. 12.  8.  9.  6.  8.  6.  1.  3.  4.  4.  1.  2.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  9.  8.  5.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  4.  1.  4.  3.  3.  2.  5.  6. 10.  8.  6.  5.  7. 10.\n  7.  8.  7.  9. 12.  8. 10.  2.  9.  5.  4.  5.  5. 11.  8.  8.  9.  6.\n  9.  9. 11. 11.  5.  9.  7.  3.  6.  6. 11.  8.  8.  9.  9.  5.  7. 10.\n  8.  7.  4.  5.  7.  4.  4.  7.  7.  9.  7.  9. 10.  6.  9.  9.  6.  8.\n  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  7.  8.  5.  6.  7. 10.  4.  7.  4.  8.\n  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  3.\n  7.  9.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.  8. 10.\n 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.  9.\n  5.  8.  3.  2.  3.  4.  4.  4.  4.  9.  9.  7.  3.  4.  8.  5.  8.  7.\n  5.  6.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7. 11.  8.\n  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.\n  4.  6.  5.  9.  8.  4.  2.  5.  7.  8.  6.  7.  7. 11.  8.  9.  5.  8.\n  4.  7.  4.  8.  6.  6.  9.  4.  5.  2. 10.  5.  8.  5.  5.  4.  7.  7.\n  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.\n  6.  9.  8.  5.  7.  4.  3.  3.  6.  2.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11.  9.\n  8.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  2.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.\n  4.  2.  4.  1.  3.  2.  5.  8.  6.  6.  8.  6.  5.  7. 10. 10.  7.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5. 11.  9. 10.  8.  9. 11.  6.\n  9.  9. 11.  9. 11.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.  9.  9.\n  8.  9.  8.  6.  3.  2.  3.  3.  3.  8.  6.  5.  5.  7. 10. 10.  5.  4.\n  5.  9.  3.  7.  5.  6. 13.  5.  7.  8.  5.  7. 10.  5.  4.  7.  4.  8.\n  5.  8.  5.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.\n  8.  3.  1.  7.  9.  5.  8.  9.  5.  4.  7.  5.  3.  3.  5.  8. 10.  6.\n  9.  8.  8. 10. 10.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  4.\n  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  9.  9.  7.  5.  3.  4.  8.  5.\n  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6.  5.  3.  5.  9.  7. 11.\n  9.  9. 10.  7.  6.  3.  5.  4.  6. 10.  4.  4.  5.  5.  7.  4.  4.  6.\n  5.  9.  3.  4.  2.  3.  5.  6.  7. 11.  9. 11.  5.  8.  4.  7.  4.  8.\n  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7.  7. 10.\n  6.  4. 10.  6.  7.  4.  4. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.\n  9.  8.  7.  5.  7.  4.  3.  3.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  8.  6.  2.  3.  4.  4.  5.  2.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  8.  5.  4.  7.  3.  6.  7.  7.  8.  2.  5.  8.  4.  8.\n  4.  7.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.  4.  4.\n  2.  4.  1.  4.  3.  3.  2.  5.  8.  6. 10.  8.  7. 10. 10.  7.  8.  7.\n  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.  9.  9.\n 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  9.  9.  5.\n  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.\n 10. 10.  4.  5.  4.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7.\n 10.  5.  4.  7.  8.  8.  5.  3.  4.  2.  9.  9.  5.  4. 12.  7.  3.  9.\n  9.  8.  8.  8.  3.  1.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.\n 10.  6.  8.  8. 10. 10.  8.  5.  4. 14.  7.  9.  8.  6.  7.  5.  4.  5.\n  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.\n  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  7. 11.\n  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10.  4.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2.  5.  8.  9.  7.\n  5.  4.  7.  7. 10.  6. 10.  6.  7.  4.  4.  6. 12.  7.  7. 10.  8.  6.\n  8.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.\n  8.  3.  7.  8.  7. 10.  9.  9.  7. 11.  6.  9.  5.  7.  6. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  3.  3.  4.  1.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.\n  6.  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  5.  8.  6.  6. 10.  8.  6.\n  5.  7. 10. 10.  7.  7. 12.  8. 10.  7.  9.  5.  4.  5.  5. 11.  9. 10.\n  8.  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6.\n 11.  8.  8.  9.  9.  5.  7. 10.  8.  7.  4.  5.  4.  4.  7.  4.  7.  5.\n  7.  9.  9. 10.  6.  9.  9.  6.  8.  9.  8.  3.  2.  1.  3.  3.  3.  8.\n  6.  5.  5.  7. 10.  4.  5.  4.  5.  7.  5.  4.  6. 13.  5.  7.  8.  5.\n  6.  7. 10.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  4.  9.  5.  4.\n  7.  3.  9.  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.\n  3.  3.  5.  8. 10.  6.  9.  8.  8. 10. 10.  8.  6. 14.  5.  7.  9.  8.\n  4.  7.  4.  5.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.\n  9.  5.  3.  5.  8.  7.  6.  3.  3.  6.  9. 11.  9.  6. 10.  5.  3.  5.\n  9.  7.  8.  9. 10.  7.  3.  7.  5.  8.  4.  6. 10. 10.  4.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.\n  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5. 10.  5.  8.  9.  7.  5.\n  4.  7.  7. 10.  6.  4. 10.  6.  7.  6. 12.  7.  7.  7. 12.  8.  6.  8.\n  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  5.  2.  6.  6.  4.  7.  5.\n  8.  3.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  5.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  1.\n  3.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  8.  2.  6.  5.  8.  4.\n  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.  4.  4.\n  2.  4.  1.  4.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5. 10. 10.  7.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  9.  9.\n 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  7.  6.  6. 11.  8.  8.  9.  9.\n  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  7.  9. 10.\n  9.  9.  6.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7. 10.\n 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6.  5.  7.  5.  6.  7.  5.  4.\n  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5. 12.  7.  3.  9.\n  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  5.\n  8. 10.  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.\n  4.  7.  4.  5.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  9.  9.\n  7.  5.  3.  4.  8.  5.  8.  7.  5.  3.  3.  2. 11.  9.  7.  6. 10.  3.\n  5.  9.  7. 11.  8.  9.  9. 10.  6.  3.  7.  5.  8.  6. 10. 10.  4.  4.\n  5.  5.  7.  4.  4.  6.  5.  9.  8.  3.  2.  3.  5.  7.  8.  6.  7.  7.\n 11.  8.  9. 11.  5.  8.  4.  7.  4.  8.  6.  4.  9.  4.  5.  2. 10.  5.\n  8.  9.  7.  5.  5.  4.  7.  7. 10.  6.  4. 10.  7.  4.  4.  6. 12.  7.\n  7.  7. 10. 12.  8.  6.  8.  7.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.\n  2.  6.  4.  7.  5.  8.  3.  7.  8. 10. 10.  7. 11. 11.  5.  6.  9.  5.\n  7.  6. 11. 10.  9. 12.  8.  9.  8.  1.  2.  3.  4.  5.  1.  2.  3.  3.\n  4.  1.  3.  3.  2.  2.  3.  2.  2.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  4.  8.  4.  7.  3.  4.  2.  3.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.\n  3.  4.  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  7.  9. 12.  8. 10.  7.  2.  5.  4.  5.  5. 11.  9. 10.\n  8.  8.  9.  9. 11.  6.  9.  9.  9. 11.  5.  9.  3.  7.  6.  6. 11.  8.\n  8.  9.  9.  5.  7. 10.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.\n  6.  9.  6.  8.  6.  3.  2.  1.  3.  3.  8.  5.  7. 10. 10.  4.  5.  4.\n  5.  9.  3.  7.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  7.  4.\n  5.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.\n  8.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.\n  9.  8.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  7.  5.  3.  4.  8.  8.\n  7.  5.  6.  3.  3.  2.  6.  9.  9.  7.  6. 10.  5.  3.  9.  7. 11.  8.\n  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.\n  7.  5.  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.\n 10. 12.  8.  6.  8.  7.  6.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  6.\n  6.  7.  5.  3.  7.  8.  7. 10. 10.  9.  9. 11. 11.  5.  9.  5.  7.  6.\n 11. 10. 12.  9.  6.  8.  6.  1.  2.  3.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  3.  2.  2.  1.  3.  2.  7.  1.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  5.  4.  7.  3.  5.  4.  7.  7.  8.  2.  6.  5.  8.\n  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  2.  3.  3.  4.  4.\n  2.  4.  4.  3.  3.  2.  8.  6.  6. 10.  6.  5.  7. 10.  8.  7.  9. 12.\n 10.  7.  2.  9.  5.  5.  5.  9. 10.  8.  8.  9.  9. 11.  6.  9. 11.  9.\n 11.  5.  7.  3.  7.  6.  6. 11.  8.  8.  9.  5.  7. 10.  8.  7.  4.  5.\n  7.  4.  4.  7.  7.  5.  7.  9.  7.  9. 10.  6.  9.  9.  6.  8.  9.  8.\n  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7. 10.  4.  5.  4.  5.  9.\n  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  7.  4.  8.  5.\n  8.  3.  4.  2.  4.  9.  9.  5.  4. 12.  7.  9.  9.  8.  8.  8.  3.  1.\n  7.  9.  5.  9.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.  8.  8. 10.\n 10.  8.  5.  4.  6. 14.  5.  9.  8.  6.  4.  7.  4.  5.  4.  6.  9.  5.\n  8.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  5.  6.  3.  2.  6.  9. 11.  9.  7. 10.  5.  3.  5.  9.  7. 11.  8.  9.\n  9. 10.  7.  6.  7.  5.  8.  4. 10. 10.  4.  4.  5.  5.  7.  4.  4.  6.\n  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7.  8.  9. 11.  5.  8.  4.  4.\n  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7. 10.\n  6.  4. 10.  6.  4.  4.  6. 12.  7.  7.  7. 10. 12.  6.  8.  7.  6.  9.\n  8.  7.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.  7.\n  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7. 11. 10.  9. 12.  8.\n  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  4.  7.  5.  6.  4.  7.  8.  2.  6.  5.  8.  4.\n  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.\n  3.  4.  4.  2.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  9.  8. 10.  7.  2.  9.  5.  4.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  6.  9. 11.  9.  5.  9.  7.  3.  7.  8.  8.  9.  9.  7. 10.\n  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  6.  5.  7. 10. 10.  4.  5.\n  5.  9.  3.  7.  5.  4. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  4.  8.\n  5.  8.  5.  3.  4.  4.  2.  4.  9.  5.  4. 12.  3.  9.  9.  8.  8.  8.\n  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  8. 10.  6.  9.  8.\n  8. 10. 10.  8.  5.  4.  6.  5.  7.  8.  6.  4.  4.  5.  4.  6.  9.  5.\n  8.  3.  2.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  5.  9.  7. 11.  8.\n  9.  9.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  4.  4.\n  5.  9.  8.  3.  4.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.  8.\n  4.  7.  4.  6.  6.  4.  4.  5.  2. 10.  8.  9.  7.  5.  5.  4.  7.  7.\n 10.  6.  4.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.\n  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  5.  8.\n  3.  7.  8.  7. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  6. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  5.  6.  4.  7.  2.  5.  8.  8.  4.  7.\n  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.  4.  4.  2.\n  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5.  9. 10.  8.  8.  9.  9.\n 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5.  7. 10.  8.  7.  5.  7.  4.  4.  7.  4.  7.  5.  9.  7.  9. 10.\n  9.  9.  6.  8.  9.  8.  3.  2.  3.  3.  3.  8.  6.  5.  5.  7. 10. 10.\n  4.  5.  4.  5.  9.  7.  5.  4.  6. 13.  5.  7.  5.  7. 10.  5.  7.  4.\n  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5. 12.  7.  3.  9.  8.  8.\n  8.  3.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5. 10.  9.  8.\n  8. 10.  8.  5.  4.  6. 14.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.  9.\n  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.\n  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.\n  7. 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  6. 10. 10.  4.  4.  7.\n  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7. 10. 12.  8.\n  8.  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  6.  6.  4.  7.\n  5.  8.  7.  8. 10. 10.  9.  7. 11. 11.  5.  6.  5.  6. 11. 10.  9. 12.\n  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  1.  3.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  2.  5.  6.  6. 10.  8.  6.  5.\n  7. 10.  7.  8.  7.  9.  8.  7.  2.  9.  5.  5. 11.  9. 10.  8.  8.  9.\n  9. 11.  6.  9.  9. 11. 11.  5.  7.  3.  7.  6.  6.  8.  8.  9.  9.  7.\n 10.  8.  7.  4.  5.  7.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7. 10. 10.\n  4.  5.  4.  5.  9.  3.  7.  5.  6.  5.  7.  8.  5.  6.  7. 10.  5.  4.\n  7.  8.  5.  8.  5.  3.  4.  4.  2.  9.  9.  5.  4. 12.  7.  3.  9.  9.\n  8.  8.  8.  3.  1.  7.  9.  5.  9.  5.  4.  7.  5.  3.  3.  5.  8. 10.\n  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.\n  5.  4.  6.  9.  5.  8.  2.  3.  4.  7.  4.  4.  4.  9.  9.  5.  3.  4.\n  8.  5.  8.  5.  6.  3.  3.  2.  6.  9.  9.  6. 10.  5.  3.  5.  7.  8.\n  9.  9. 10.  7.  6.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.\n  4.  6.  5.  9.  8.  4.  2.  3.  7.  8.  6.  7.  7.  8.  9. 11.  5.  4.\n  7.  4.  8.  6.  6.  4.  9.  4.  5. 10.  5.  8.  9.  7.  5.  5.  4.  7.\n  7. 10.  6.  4. 10.  6.  7.  4.  4. 12.  7.  7.  7. 12.  8.  6.  8.  7.\n  6.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.  2.  6.  4.  7.  5.  8.  3.\n  7.  7. 10.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.  9. 12.  8.\n  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  3.\n  3.  4.  4.  2.  4.  1.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.\n  8.  8.  9.  9. 11.  6.  9.  9.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.\n  8.  9.  9.  5.  7.  7.  4.  7.  4.  4.  7.  4.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10.\n 10.  4.  5.  4.  5.  3.  7.  5.  4.  6. 13.  8.  5.  6.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  4.  4.  2.  4.  9.  9.  5.  4. 12.  9.  9.  8.\n  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8.\n  6.  9.  8. 10. 10.  8.  5.  4.  6.  5.  7.  9.  6.  4.  7.  4.  5.  4.\n  5.  8.  3.  2.  3.  4.  4.  4.  4.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  5.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  9. 11.  8.  9.  9.\n 10.  7.  6.  3.  7.  5.  8.  4.  6. 10.  4.  4.  5.  5.  7.  4.  6.  8.\n  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.  8.  4.  7.\n  4.  8.  6.  6.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7.  7.\n 10.  6.  4. 10.  6.  7.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  2.  2.  1.  3.  2.  7.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 8.  4.  4.  8.  5.  4.  7.  3.  6.  7.  7.  8.  2.  6.  5.  8.  4.  8.\n  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.  4.\n  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.\n  7.  8.  9. 12.  8. 10.  7.  9.  5.  4.  5. 11.  9. 10.  8.  8.  9.  9.\n 11.  6.  9.  9. 11.  9.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  9.\n  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  4.  7.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  8.  8.  6.  2.  1.  3.  3.  3.  8.  5.  5.  7. 10. 10.\n  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.\n  4.  7.  4.  5.  5.  3.  4.  4.  2.  4.  9.  4. 12.  7.  3.  9.  9.  8.\n  8.  3.  1.  9.  5.  8.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.\n  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.\n  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.\n  4.  5.  8.  7.  5.  6.  3.  3.  6.  9. 11.  9.  7.  6.  5.  3.  5.  9.\n  7. 11.  8.  9. 10.  7.  6.  3.  7.  5.  8.  4. 10. 10.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  4.  5.  2. 10.  5.  8.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10.\n 12.  6.  8.  7.  6.  9.  8.  7.  7.  4.  3.  3.  6.  5.  2.  6.  6.  4.\n  7.  5.  8.  3.  8.  7. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6.\n 11. 10.  9. 12.  8.  9.  8.  6.  1.  2.  3.  4.  2.  3.  4.  1.  3.  3.\n  2.  2.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  6.  5.\n  8.  4.  8.  4.  7.  3.  4.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  4.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.\n  7. 10. 10.  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.\n  9. 10.  8.  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  7.  6.\n 11.  8.  8.  9.  9.  5. 10.  8.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.\n  9.  7.  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.\n  8.  6.  5.  5. 10. 10.  4.  5.  4.  9.  3.  5.  4. 13.  5.  7.  8.  5.\n  6.  7.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  2.  4.  9.  9.  5.  4.\n 12.  7.  3.  9.  9.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  5.\n  5.  8. 10.  6.  9.  8.  8. 10. 10.  5.  4.  6. 14.  5.  7.  9.  8.  6.\n  4.  7.  4.  5.  4.  6.  9.  5.  3.  2.  7.  4.  4.  9.  9.  7.  3.  4.\n  8.  5.  8.  7.  5.  6.  3.  2.  6. 11.  9.  7.  6. 10.  5.  3.  5.  9.\n  7. 11.  8.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.\n  5.  7.  4.  4.  6.  5.  9.  8.  3.  4.  3.  5.  7.  8.  6.  7. 11.  8.\n  9. 11.  5.  8.  7.  4.  8.  6.  6.  4.  9.  5.  2.  8.  9.  7.  5.  5.\n  4.  7.  7. 10.  6.  4.  7.  4.  4.  6. 12.  7.  7.  7. 10.  8.  6.  8.\n  7.  6.  9.  7.  5.  4.  3.  3.  2.  5.  2.  6.  4.  7.  5.  8.  3.  7.\n  8.  7. 10. 10.  9.  9.  7. 11. 11.  6.  9.  5.  7.  6. 11. 10.  9. 12.\n  8.  9.  6.  8.  6.  1.  3.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  8.  4.  7.  3.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  1.  4.  3.  3.  2.  5.  8.  6. 10.  6.  5.  7. 10.\n 10.  7.  8.  7.  9. 12.  8. 10.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.\n  8.  9.  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  3.  6.  6. 11.  8.  8.\n  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.\n  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  1.  3.  3.  3.  6.  5.  7.\n 10. 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  6.  7.\n 10.  5.  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4.\n 12.  7.  3.  9.  9.  8.  8.  8.  3.  1.  7.  5.  8.  9.  5.  2.  4.  7.\n  5.  3.  3.  8. 10.  6.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.\n  8.  6.  4.  7.  4.  5.  4.  6.  9.  5.  8.  3.  3.  4.  7.  4.  4.  9.\n  9.  7.  5.  3.  4.  8.  5.  8.  7.  5.  6.  3.  2.  6.  9. 11.  9.  7.\n  6. 10.  5.  3.  5.  9.  7. 11.  8.  9.  9. 10.  7.  3.  7.  5.  4.  6.\n 10. 10.  4.  5.  5.  7.  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.\n  8.  6.  7. 11.  8.  8.  4.  7.  4.  8.  6.  4.  9.  4.  2. 10.  5.  9.\n  7.  5.  5.  4.  7.  7. 10.  6. 10.  6.  4.  4.  6. 12.  7.  7.  7. 10.\n 12.  8.  6.  8.  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  2.  6.\n  6.  4.  7.  5.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  9.  7.\n  6. 10.  9. 12.  8.  9.  6.  8.  1.  2.  4.  4.  5.  1.  3.  3.  4.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  8.  4.  8.  4.  7.  3.  4.  2.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  4.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6. 10. 10.  7.\n  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5.  7. 10.  8.  7.  4.  5.  4.  4.  7.  7.  5.  7.  9.  9. 10.  6.\n  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7.\n 10. 10.  5.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6. 10.  5.\n  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.\n  3.  9.  9.  8.  8.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  3.  3.  5.\n  8. 10.  6.  9.  8.  8. 10.  8.  4.  6. 14.  5.  9.  8.  4.  7.  4.  5.\n  4.  6.  9.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  7.  5.  3.  4.  8.\n  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7. 10.  3.  5.  9.  7. 11.\n  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10.  4.  4.  5.  5.  7.\n  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.\n  9. 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.\n  9.  7.  5.  4.  7.  7.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7.\n 10. 12.  8.  6.  6.  9.  8.  5.  7.  4.  3.  6.  2.  5.  2.  6.  6.  4.\n  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6.\n 11. 10.  9. 12.  8.  9.  6.  6.  2.  3.  4.  4.  5.  1.  2.  3.  4.  1.\n  3.  3.  2.  1.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  6.\n  3.  4.  4.  2.  4.  1.  4.  3.  3.  5.  8.  6.  6.  8.  5.  7. 10.  7.\n  8.  7. 12. 10.  7.  2.  5.  4.  5. 11.  9.  9.  9. 11.  6.  9.  9. 11.\n  9. 11.  9.  7.  3.  7.  6. 11.  8.  8.  9.  9.  5.  7. 10.  8.  7.  4.\n  5.  7.  4.  4.  7.  4.  7.  7.  9.  7.  9. 10.  6.  9.  9.  8.  9.  6.\n  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.  5.  4.  5.  9.  3.\n  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  7.  4.  8.  5.\n  8.  5.  3.  4.  4.  4.  9.  9.  5.  4.  7.  3.  9.  9.  8.  8.  8.  3.\n  1.  7.  9.  8.  9.  5.  2.  7.  5.  3.  3.  5.  8. 10.  6.  9.  8. 10.\n 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  5.  4.  6.  9.  5.  8.\n  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.  8.  7.\n  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7. 11.  9.\n  9. 10.  7.  6.  3.  8.  4.  6. 10. 10.  4.  4.  5.  5.  4.  4.  6.  5.\n  9.  8.  3.  4.  2.  5.  7.  6.  7.  7. 11.  9. 11.  5.  8.  4.  7.  4.\n  8.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.  4.  7. 10.  4.\n 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.  9.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.\n  9. 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.\n  1.  3.  3.  2.  2.  1.  3.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  4.  9.  8.  5.  4.  7.  3.  5.  4.  7.  8.  2.  6.  5.  8.  4.  4.\n  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.  4.\n  4.  2.  4.  1.  4.  2.  5.  8.  6. 10.  8.  6.  5.  7. 10. 10.  7.  8.\n  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11. 10.  8.  8. 11.  6.\n  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  7.  4.  7.  5.  7.  7.  9.  6.  9.  9.  6.\n  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  7. 10.  4.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  4.\n  8.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.\n  8.  8.  3.  1.  7.  9.  5.  8.  9.  2.  4.  7.  5.  3.  3.  5.  8. 10.\n  6.  9.  8.  8. 10. 10.  8.  5.  4. 14.  5.  7.  9.  8.  6.  4.  7.  4.\n  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  9.  9.  7.  5.  8.  5.  7.\n  5.  6.  3.  3.  2.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7. 11.  8.\n  9.  9.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.\n  5.  8.  4.  7.  4.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  5.  4.\n  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7. 10. 12.  8.  6.  8.\n  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.\n  5.  8.  3.  7.  8.  7. 10. 10.  9.  9. 11. 11.  5.  6.  9.  5.  7.  6.\n 11. 10. 12.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  3.  2.  2.  1.  2.  7.  1.  2.  1.  2.  2.  1.  1.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  3.  4.  2.  3.  2.  2.  5.  4.  2.  6.  3.  3.  4.  2.  4.\n  1.  4.  3.  3.  2.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  7.  8.  7.\n  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.  9.  9.\n  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10.  4.  4.\n  5.  9.  3.  7.  4.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.  7.  4.\n  8.  5.  8.  3.  4.  2.  4.  9.  5.  4. 12.  7.  3.  9.  8.  8.  8.  3.\n  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.  9.\n  8.  8. 10. 10.  8.  5.  6. 14.  5.  7.  8.  6.  4.  7.  4.  5.  4.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.\n  5.  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  7.  6. 10.  5.  5.  9.  7.\n 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.\n  5.  7.  4.  4.  5.  9.  3.  4.  2.  3.  5.  8.  7.  7. 11.  8.  9. 11.\n  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.\n  5.  5.  7.  7. 10.  6.  4. 10.  6.  7.  4.  6.  7.  7.  7. 10. 12.  8.\n  6.  8.  7.  6.  9.  8.  7.  5.  7.  3.  3.  6.  2.  5.  2.  6.  6.  7.\n  5.  8.  3.  7.  8.  7. 10. 10.  9.  9.  7.  5.  6.  9.  5.  7.  6. 11.\n  9.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  1.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  2.  6.  3.\n  3.  4.  4.  2.  4.  1.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  9. 12.  8. 10.  7.  2.  9.  4.  5.  5. 11. 10.  8.  8.\n  9.  9. 11.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.\n  7.  9. 10.  6.  9.  9.  6.  8.  6.  3.  1.  3.  3.  3.  8.  6.  5.  5.\n  7. 10. 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.\n  6.  7.  5.  4.  7.  4.  5.  8.  3.  4.  4.  2.  5.  4. 12.  7.  3.  9.\n  9.  8.  8.  3.  1.  7.  9.  5.  9.  5.  4.  7.  3.  3.  5.  8. 10.  6.\n  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  9.  6.  4.  7.  4.  5.  4.\n  6.  9.  5.  8.  3.  3.  4.  4.  4.  9.  9.  7.  5.  3.  8.  5.  8.  7.\n  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9. 11.  9.\n 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8. 11.  5.\n  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10.\n  6.  7.  9.  8.  5.  7.  4.  3.  3.  2.  5.  2.  6.  6.  4.  7.  5.  3.\n  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7. 11. 10.  9.\n 12.  8.  6.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  4.  1.  3.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  8.  4.  7.  3.  5.  6.  4.  7.  8.  2.  5.  8.  4.  8.\n  7.  3.  4.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.  4.  2.\n  4.  1.  4.  3.  2.  5.  8.  6. 10.  8.  6.  5. 10. 10.  7.  8.  7.  9.\n 12.  8. 10.  7.  2.  9.  5.  5.  5. 11.  9. 10.  8.  8.  9.  9. 11.  6.\n  9.  9. 11.  9. 11.  5.  9.  7.  3.  6.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  7.  9.  9. 10.  6.  9.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  7. 10.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.  5.  6. 10.  5.  4.  7.  4.\n  8.  5.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  8.  8.\n  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5. 10.  6.  9.\n  8.  8. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.\n  6.  9.  5.  8.  3.  2.  3.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.\n  5.  8.  7.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.\n  7. 11.  8.  9.  9.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  7.\n  4.  4.  6.  5.  9.  8.  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  4.  2. 10.  5.  8.  7.  5.  5.\n  7.  7. 10.  6.  4. 10.  6.  7.  4.  4. 12.  7.  7. 10. 12.  8.  6.  8.\n  7.  6.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.\n  8.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 10.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  2.  2.  3.  2.  7.  1.  2.  1.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 8.  4.  9.  8.  5.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.  4.  8.\n  4.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.  3.  4.  4.  2.\n  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  7.\n  7. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.  9.  9.\n 11.  6.  9. 11. 11.  5.  9.  7.  3.  7.  6. 11.  8.  8.  9.  9.  5.  7.\n 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  7.  9. 10.  6.  9.\n  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7. 10. 10.  4.\n  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  8.  5.  6.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4.  7.  3.  9.\n  9.  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.\n  5.  8. 10.  6.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.\n  7.  4.  5.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  9.  9.  7.\n  5.  3.  4.  5.  8.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  6. 10.  5.\n  5.  9.  7. 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4. 10.  4.  4.\n  5.  4.  4.  6.  5.  9.  3.  4.  2.  5.  7. 11.  8.  9. 11.  8.  4.  7.\n  4.  8.  6.  6.  4.  9.  4.  5.  2.  5.  8.  9.  7.  5.  4.  7.  7.  6.\n  4.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.  9.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  6.  4.  7.  5.  8.  3.\n  7.  8.  7. 10. 10.  9.  9. 11.  5.  9.  5.  7.  6. 11. 10.  9. 12.  8.\n  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  2.  3.  3.  4.  1.  3.  3.  2.\n  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  8.  4.  7.  3.  4.  2.  3.  2.  2.  5.  5.  4.  4.  4.  6.  3.\n  3.  4.  2.  4.  1.  4.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10.\n 10.  7.  8.  7.  9. 12.  8. 10.  2.  9.  5.  4.  5.  5.  9. 10.  8.  9.\n  9. 11.  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  9.  5.  7. 10.  8.  7.  4.  5.  7.  4.  4.  4.  7.  5.  7.  9.  7.\n  9. 10.  6.  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.\n  5.  7. 10. 10.  4.  5.  4.  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  8.\n  5.  6.  7. 10.  5.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.\n  5.  4. 12.  7.  3.  9.  9.  8.  8.  8.  3.  1.  9.  5.  8.  9.  5.  2.\n  5.  3.  3.  5.  8. 10.  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.\n  7.  9.  8.  4.  4.  5.  4.  6.  5.  8.  2.  3.  4.  7.  4.  4.  9.  7.\n  5.  3.  4.  8.  5.  7.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.\n  3.  5.  9.  7. 11.  8.  9.  9. 10.  7.  6.  7.  5.  8.  4.  6. 10. 10.\n  4.  4.  5.  5.  7.  4.  6.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.\n  7. 11.  9. 11.  5.  8.  4.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.\n  5.  8.  9.  5.  5.  4.  7. 10.  6. 10.  6.  4.  4.  6. 12.  7.  7.  7.\n 10. 12.  8.  6.  8.  7.  6.  8.  7.  7.  4.  3.  3.  6.  2.  5.  6.  6.\n  4.  7.  5.  8.  3.  7.  8.  7. 10. 10.  9.  7. 11. 11.  5.  6.  9.  5.\n  6. 11. 10.  9. 12.  8.  9.  6.  8.  1.  3.  4.  4.  5.  1.  3.  4.  1.\n  3.  2.  1.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  5.  6.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  5.  2.  5.  5.  4.  4.  4.  2.  6.  4.  4.\n  2.  4.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7. 10. 10.  7.\n  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.  8.\n  9.  9. 11.  6.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.\n  9.  5.  7. 10.  8.  7.  7.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  6.\n  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  6.  5.  5.  7. 10.\n 10.  4.  5.  5.  9.  3.  7.  5.  4.  6.  5.  7.  8.  6.  7. 10.  5.  4.\n  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  4. 12.  7.  3.  9.  9.\n  8.  8.  8.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8.\n 10.  6.  9.  8. 10. 10.  8.  5.  5.  7.  9.  8.  6.  4.  7.  4.  5.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  4.  8.  5.\n  8.  5.  6.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7.\n 11.  8.  9.  9. 10.  7.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.  5.\n  7.  4.  6.  5.  9.  8.  3.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9.\n 11.  5.  8.  4.  7.  4.  8.  6.  4.  9.  5.  2. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 12.\n  8.  6.  8.  7.  6.  9.  8.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.\n  6.  7.  5.  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11.  5.  6.  9.  7.\n  6. 11. 10.  9.  8.  9.  8.  6.  1.  2.  3.  4.  5.  1.  2.  3.  3.  4.\n  3.  3.  2.  2.  1.  3.  7.  1.  2.  1.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  6.  4.  7.  7.  8.  2.  6.  5.\n  8.  4.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  4.  4.  4.  2.  3.  3.\n  4.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  6.  5.  7. 10. 10.  8.\n  7.  9.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9.  8.  8.  9.  9. 11.\n  6.  9.  9. 11.  9. 11.  5.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.  5.\n  7. 10.  8.  4.  5.  7.  4.  4.  7.  4.  5.  7.  9.  7.  6.  9.  6.  8.\n  9.  8.  2.  3.  3.  3.  8.  6.  5.  5.  7. 10.  4.  5.  4.  5.  9.  3.\n  7.  5.  4.  6. 13.  7.  8.  5.  6.  7. 10.  5.  4.  7.  8.  5.  8.  5.\n  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.  8.  3.\n  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.  8.  6.  9.  8.\n  8. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  4.  5.  4.  6.\n  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  3.  4.  8.  5.\n  8.  7.  5.  6.  3.  2.  6. 11.  7.  6. 10.  5.  3.  5.  9.  7. 11.  8.\n  9.  9. 10.  7.  6.  3.  7.  5.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.\n  4.  5.  9.  8.  3.  4.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.\n  8.  4.  7.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  4.\n  7.  7. 10.  6.  4. 10.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.\n  8.  7.  6.  9.  7.  5.  7.  4.  3.  3.  6.  2.  5.  2.  6.  4.  7.  5.\n  8.  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  6.  5.  7.  6. 11.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  5.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  2.  6.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.  6.\n  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  2.  8.  6.  6. 10.  8.  6.  5.\n  7.  7.  8.  7.  9. 12.  8.  7.  9.  5.  4.  5. 11.  9. 10.  8.  8.  9.\n  9. 11.  6.  9.  9. 11.  9. 11.  9.  7.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5. 10.  8.  7.  4.  5.  7.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9.\n 10.  6.  9.  9.  8.  9.  8.  6.  3.  2.  1.  3.  3.  8.  6.  5.  5.  7.\n 10. 10.  4.  4.  3.  7.  5.  6. 13.  5.  7.  8.  5.  6.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  3.  4.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.\n  8.  8.  8.  3.  1.  7.  9.  5.  8.  9.  5.  2.  4.  7.  5.  3.  3.  5.\n  8. 10.  6.  9.  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.\n  4.  7.  4.  4.  6.  9.  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.\n  7.  5.  3.  4.  8.  5.  8.  7.  5.  6.  3.  2.  6.  9. 11.  9.  7.  6.\n  5.  3.  9.  7. 11.  8.  9. 10.  7.  6.  3.  5.  8.  4.  6. 10. 10.  4.\n  5.  5.  7.  4.  4.  6.  5.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7.\n 11.  8.  9.  5.  7.  4.  8.  6.  6.  4.  9.  4.  5.  2. 10.  5.  9.  7.\n  5.  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  6. 12.  7.  7.  7. 10.\n 12.  8.  6.  8.  7.  6.  9.  8.  7.  5.  7.  3.  3.  6.  5.  2.  6.  6.\n  4.  7.  5.  8.  3.  7.  8.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11.\n 10.  9. 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  5.  1.  2.  3.  3.\n  1.  3.  3.  2.  2.  1.  3.  2.  2.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.\n  5.  8.  4.  8.  4.  7.  3.  2.  3.  5.  2.  2.  5.  5.  4.  4.  4.  2.\n  6.  3.  3.  4.  4.  2.  4.  1.  4.  3.  3.  5.  8.  6.  8.  5.  7. 10.\n 10.  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5. 11.  9. 10.  8.\n  9. 11.  6.  9.  9. 11.  9.  5.  9.  7.  7.  6. 11.  9.  9.  5.  7. 10.\n  7.  4.  5.  4.  4.  7.  4.  7.  5.  7.  9.  7.  9. 10.  9.  9.  6.  8.\n  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  7. 10. 10.  4.  5.  4.\n  5.  9.  3.  7.  5.  4.  6. 13.  5.  7.  5.  6.  7. 10.  4.  7.  4.  8.\n  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  7.  3.  9.  9.  8.  8.\n  8.  3.  7.  9.  8.  5.  2.  4.  7.  5.  3.  3.  8. 10.  6.  9.  8.  8.\n 10. 10.  8.  5.  4.  6. 14.  5.  7.  9.  8.  6.  4.  7.  5.  4.  9.  3.\n  2.  3.  4.  7.  4.  4.  4.  9.  5.  3.  4.  8.  5.  8.  7.  5.  6.  3.\n  3.  9. 11.  9.  7.  6. 10.  5.  3.  5.  7.  8.  9.  9. 10.  7.  6.  3.\n  7.  8.  4.  6. 10. 10.  4.  4.  5.  5.  7.  4.  4.  6.  5.  9.  8.  3.\n  4.  2.  3.  5.  7.  8.  6.  7.  7. 11.  8.  9. 11.  5.  8.  4.  7.  4.\n  8.  6.  4.  9.  4.  5.  2. 10.  8.  9.  7.  5.  5.  4.  7.  7. 10.  4.\n 10.  6.  7.  4.  4.  6. 12.  7.  7.  7. 10. 12.  8.  6.  8.  7.  6.  9.\n  8.  7.  5.  7.  4.  3.  3.  6.  2.  2.  6.  6.  4.  7.  5.  8.  3.  8.\n  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.  9. 12.\n  8.  9.  6.  8.  6.  1.  2.  4.  4.  5.  1.  2.  3.  3.  4.  1.  3.  3.\n  2.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  8.  4.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  8.  2.  6.  5.\n  8.  4.  7.  3.  4.  2.  3.  5.  2.  5.  5.  4.  4.  4.  2.  6.  3.  3.\n  4.  4.  2.  4.  1.  4.  3.  3.  2.  5.  8.  6.  6. 10.  8.  6.  5.  7.\n 10. 10.  7.  8.  7.  9. 12. 10.  7.  2.  5.  4.  5.  5. 11.  9. 10.  8.\n  8.  9. 11.  6.  9.  9. 11.  9. 11.  5.  3.  7.  6.  6. 11.  8.  8.  9.\n  9.  5.  7.  8.  7.  4.  5.  7.  4.  4.  7.  7.  5.  7.  9.  7.  9. 10.\n  6.  9.  9.  6.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  6.  5.  5.  7.\n 10. 10.  4.  5.  4.  5.  9.  4.  6. 13.  5.  7.  8.  5.  7. 10.  5.  4.\n  7.  4.  8.  5.  8.  5.  4.  2.  4.  9.  9.  5. 12.  7.  9.  9.  8.  8.\n  8.  3.  1.  7.  9.  5.  8.  9.  2.  4.  7.  5.  3.  3.  5.  8. 10.  6.\n  9.  8.  8. 10. 10.  4.  6. 14.  7.  9.  8.  6.  7.  4.  5.  4.  6.  9.\n  5.  8.  3.  2.  3.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.  5.\n  8.  7.  5.  6.  3.  3.  2.  6.  9.  9.  7. 10.  5.  3.  5.  9.  7. 11.\n  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  6. 10.  4.  5.  5.  7.  4.  4.\n  6.  5.  9.  8.  3.  4.  2.  3.  5.  7.  8.  6.  7.  7.  8.  9. 11.  5.\n  8.  4.  7.  4.  6.  6.  4.  9.  4.  5.  2. 10.  5.  8.  9.  7.  5.  5.\n  4.  7. 10.  6.  4. 10.  6.  7.  4.  4.  6. 12.  7. 10. 12.  8.  8.  7.\n  6.  9.  8.  7.  5.  4.  3.  3.  6.  2.  5.  2.  6.  4.  7.  5.  8.  3.\n  7.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11. 10.  9.\n 12.  8.  9.  6.  8.  6.  1.  2.  3.  4.  4.  1.  2.  3.  3.  4.  1.  3.\n  3.  2.  2.  1.  3.  2.  7.  1.  1.  2.  2.  1.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n8 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n    super().fit(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/tree/_classes.py\", line 172, in fit\n    X, y = self._validate_data(\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/base.py\", line 591, in _validate_data\n    X = check_array(X, input_name=\"X\", **check_X_params)\n  File \"/home/rios/.local/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 879, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[ 2.  4.  9.  8.  5.  4.  7.  3.  5.  6.  4.  7.  7.  8.  2.  6.  5.  8.\n  4.  8.  4.  7.  3.  4.  2.  3.  5.  2.  2.  5.  5.  4.  4.  2.  6.  3.\n  3.  4.  2.  4.  1.  4.  3.  3.  2.  5.  6.  6. 10.  8.  6.  7. 10. 10.\n  7.  8.  7.  9. 12.  8. 10.  7.  2.  9.  5.  4.  5.  5. 11.  9. 10.  8.\n  8.  9.  9.  6.  9.  9.  9. 11.  5.  9.  7.  3.  7.  6.  6.  8.  8.  9.\n  9.  7. 10.  8.  7.  4.  5.  7.  4.  7.  4.  7.  5.  9.  7.  9. 10.  6.\n  9.  9.  6.  8.  9.  8.  6.  3.  2.  1.  3.  3.  3.  8.  5.  5. 10. 10.\n  4.  5.  4.  5.  9.  3.  7.  5.  4. 13.  5.  7.  8.  5.  6.  7. 10.  5.\n  4.  7.  4.  8.  5.  8.  5.  3.  4.  4.  2.  4.  9.  9.  5.  4. 12.  3.\n  9.  8.  8.  3.  1.  7.  5.  8.  9.  5.  2.  4.  7.  5.  5.  8. 10.  9.\n  8.  8. 10. 10.  8.  5.  4.  6. 14.  5.  7.  8.  6.  4.  7.  4.  5.  4.\n  6.  9.  5.  8.  3.  2.  4.  7.  4.  4.  4.  9.  9.  7.  5.  3.  4.  8.\n  8.  7.  5.  3.  3.  2.  6.  9. 11.  9.  7.  6. 10.  5.  3.  5.  9.  7.\n 11.  8.  9.  9. 10.  7.  6.  3.  7.  5.  8.  4.  6. 10. 10.  4.  4.  5.\n  5.  7.  4.  4.  6.  5.  9.  8.  3.  4.  2.  3.  7.  8.  6.  7. 11.  8.\n  9. 11.  5.  8.  4.  4.  8.  6.  6.  9.  4.  5. 10.  5.  8.  9.  7.  5.\n  5.  4.  7.  7. 10.  6.  4. 10.  6.  7.  4.  6.  7.  7.  7. 10. 12.  8.\n  6.  8.  6.  9.  8.  7.  5.  7.  4.  3.  6.  2.  5.  2.  6.  6.  4.  8.\n  3.  7.  8.  7. 10. 10.  9.  9.  7. 11. 11.  5.  6.  9.  5.  7.  6. 11.\n 10.  9. 12.  9.  6.  8.  6.  2.  3.  4.  4.  5.  1.  2.  3.  3.  4.  1.\n  3.  3.  2.  1.  3.  2.  7.  1.  2.  1.  2.  2.  1.  2.].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n"
     ]
    }
   ],
   "source": [
    "def RSDT(X_train, y_train, X_test, y_test, prob=False, metric = 'auc'):\n",
    "    params = {'max_depth':np.arange(1, 3, 1), \n",
    "              'criterion':np.array(['gini', 'entropy']),\n",
    "              'min_samples_leaf':np.arange(1, 3, 1)\n",
    "             }    \n",
    "   \n",
    "    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)\n",
    "    model = DecisionTreeClassifier()\n",
    "    model_cv = RandomizedSearchCV(model, params, cv = cv, scoring='f1_macro', n_jobs = -1, n_iter=50)\n",
    "\n",
    "    model_cv.fit(X_train, y_train)\n",
    "    \n",
    "    if prob:\n",
    "        y_pred = model_cv.predict_proba(X_test)\n",
    "    else:\n",
    "        y_pred = model_cv.predict(X_test)\n",
    "    \n",
    "    return y_pred\n",
    "\n",
    "\n",
    "acc, f1, auc, pred = SynClass(x_train, y_train, x_test, y_test, learner = RSDT, scoring = 'auc', classThreshold = 0.5, probability = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/rios/projects/thrombosis/src/classification/sfc.py:131: RuntimeWarning: invalid value encountered in long_scalars\n",
      "  acc_neg = tn / (tn + fn)\n"
     ]
    }
   ],
   "source": [
    "# NÃƒO RODAR\n",
    "# teste bÃ¡sico de validaÃ§Ã£o com o cÃ³digo em R\n",
    "def runR(x_train, y_train, x_test, y_test, prob=False, metric = 'auc'):   \n",
    "\n",
    "    xgb_R = pd.read_csv(\"/tmp/output_xgb.csv\", sep=\",\", index_col=[0])\n",
    "    xgb_R.reset_index(drop=True, inplace=True)\n",
    "    return xgb_R\n",
    "\n",
    "acc, f1, auc, pred = SynClass(x_train, y_train, x_test, y_test, learner = runR, scoring = 'auc', classThreshold = 0.5, probability = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
